### ISSUE TITLE
rate_limit does not seem to be limiting the request rate to Vultr properly preventing the use of -parallelism=24

### ISSUE THREAD

**Issue by Obsecurus** [vultr/terraform-provider-vultr#1]
Vultr has a horribly slow request rate limit at 2/sec. So when using this provider driver combined with other providers or have a node count higher than 2-3 it generates rate limit errors even on `terraform plan`. You have to end up using `terraform plan -parallelism=3` so it even works slowing down your overall deployment considerably. The only workaround I have found is to add a provisioner for a local 10 minute sleep after each vultr server deploy and separately creating a plan file first. However, this is unreliable. 
`provisioner "local-exec" {
      command = "sleep 600"
  }`

**Comment by Obsecurus** [comment]
so essentially the provider plugin should handle this rate limit gracefully

**Comment by Obsecurus** [comment]
Found the rate_limit setting in the driver. This should probably have a default setting.

**Comment by Obsecurus** [comment]
See https://github.com/terraform-providers/terraform-provider-vultr/blob/master/vultr/provider.go you can specify it in provider as rate_limit = 3.

**Comment by ddymko** [comment]
Hey @Obsecurus 

There actually is already a default for the rate limit which is 600ms. This is being pulled from the underlying go client `govultr`

https://github.com/vultr/govultr/blob/master/govultr.go#L19

You are also able to set your own rate_limit in the in the provider section as such

```hcl
provider "vultr" {
  api_key = "VULTR_API_KEY"
  rate_limit = 700 
}
```
This 700 would be 700 milliseconds so if you wanted to do 3 seconds then set the rate limit to 3000.

https://github.com/terraform-providers/terraform-provider-vultr/blob/master/website/docs/index.html.markdown

Now, we know that this ratelimit isn't the best solution currently in place. It is part of the V1 API design which limits you to 3 r/s. We have two solutions currently planned to address this issue a short term and long term solution to address this.

Short term - implement a retry mechanism to retry the failed calls which are being hit by the API ratelimit 

Long term - V2 API...this would be a new implementation of the API which would have a more robust rate limit and a more modern design 

Hopefully this helps clear up some confusion and gives you an idea of the steps we are taking to improve upon this!

**Comment by Obsecurus** [comment]
@ddymko thanks for the quick reply. So even if I set it to something like:
```
provider "vultr" {
  api_key = "VULTR_API_KEY"
  rate_limit = 2 
}
```
`terraform plan -parallelism=48` or even 24 or 32 causes `Rate limit reached - please try your request again later.  Current rate limit: 3 requests/sec`

**Comment by ddymko** [comment]
@Obsecurus 

Are you trying to set the rate limit to 2 seconds? If so it would have to be `rate_limit = 2000`

**Comment by Obsecurus** [comment]
@ddymko just trying to get it working. I have tried various tuning from -2000 - 10000. I think there might be a bug in provider.go where it is multiplying this number out so it is not actually applying the rate limit or something. I've tried -2000,100,200,500,700,2000,3000,10000. I need to slow the client down so even under parallelism is doesn't cause the rate limit reached error.

**Comment by Obsecurus** [comment]
For reference:
```
Terraform v0.12.12
+ provider.aws v2.33.0
+ provider.digitalocean v1.9.1
+ provider.google v2.18.1
+ provider.linode v1.8.0
+ provider.openstack v1.24.0
+ provider.vultr v1.0.5
```

**Comment by Obsecurus** [comment]
Also the only resource I am deploying at vultr is a vultr_server with a count of 2 at each region. Each region is defined in a separate module.

**Comment by Obsecurus** [comment]
This line is what I was referencing as a potential bug: https://github.com/terraform-providers/terraform-provider-vultr/blob/b8a6cb7add72061abcb59627067d748896a7fe0c/vultr/config.go#L46

**Comment by ddymko** [comment]
@Obsecurus 

hmmm that is odd I'll look into this and see if there is anything that isn't working properly with the ratelimit. From using it internally we haven't seen this behavior but I will dig into this for you!

The  vultrClient.SetRateLimit expects to receive a `time.Duration` and the provider takes the number you pass in and converts it to milliseconds

https://github.com/vultr/govultr/blob/master/govultr.go#L232

Our ratelimit is definitely a pain point for us so the short term solution of having the retry mechanism in place should alleviate some of the burden.

**Comment by Obsecurus** [comment]
Okay. I'm not aware of a strategy to implement retries in terraform within the module other than modifying the provider plugin directly via https://www.terraform.io/docs/extend/resources/retries-and-customizable-timeouts.html

**Comment by ddymko** [comment]
This is something I am looking to implement within the go client itself.

https://github.com/vultr/govultr

Reason being since the go client executes calls on our behalf it should also retry on our behalf if we hit the ratelimit. This would then be inherited into any tool/application that sits on top of the go client

**Comment by Obsecurus** [comment]
Okay so sounds like the 2 issues are that rate_limit is not being applied via the vultr provider configuration and retry needs added to govultr. Can you hold this open and close once one or both of those are resolved? We're just going to have to drop Vultr as one of our providers for now until this is resolved unfortunately. Thanks for the help/info!

**Comment by ddymko** [comment]
I will keep this open and use this to address any PRs ill make. 

As for issues:

- The rate_limit in your case not being properly applied. Although if I set my rate_limit to `10000` it does wait 10 seconds in between calls. I will still dig into this one for you though.

- The retry to govultr is an enhancement which will improve user experience

**Comment by Obsecurus** [comment]
Okay for reference this was happening with 90-180 nodes (6-12 per region) depending on my configuration and the only resource was vultr_server and the highest count was ever set to was 2 for a single vultr_server resource.

**Comment by Obsecurus** [comment]
@ddymko does this mean the vultr provider just needs setup with the new version of govultr?

**Comment by pgaskin** [comment]
@Obsecurus, yes, once it is released. You can also manually update it to the latest commit.

**Comment by ddymko** [comment]
@Obsecurus

We are going to update terraform and run through make sure everything is working properly and then cut a release shortly thereafter

**Comment by Obsecurus** [comment]
@ddymko any plans to close this one out soon? Seems like the govultr fix has been merged.
