### ISSUE TITLE
[BUG] - plan does not accept values.

### ISSUE THREAD

**Issue by evanrich** [vultr/terraform-provider-vultr#100]
Trying to get started using this with the following resource:

```
resource "vultr_instance" "website_instance" {
    plan = "400"
    region = "sjc"
    os_id = "387"
    hostname = "website"
    label = "website"
}
```

Per the documentation, it says plan = id of the plan, although curling the api shows me something like this:
```
"400": {
        "VPSPLANID": "400",
        "name": "1024 MB RAM,32 GB SSD,1.00 TB BW",
        "vcpu_count": "1",
        "ram": "1024",
        "disk": "32",
        "bandwidth": "1.00",
        "bandwidth_gb": "1024",
        "price_per_month": "6.00",
        "plan_type": "HIGHFREQUENCY"
    }
```

I have tried setting the "plan to  "400", the name, etc. and nothing works.  in the documentation, the example lists " plan = "vc2-1c-1gb", I've tried that except "vc2z", since I'm interested in high frequency, but this also doesn't seem to work.  Got the list from here:
```
curl https://api.vultr.com/v1/plans/list_vc2z|python -m json.tool
```
Any thoughts?

**Comment by mamclaughlin** [comment]
Hey, 

Thanks for reaching out! The current version of our plugin leverages our [v2 API](https://www.vultr.com/api/v2/) which features some new naming conventions. High frequency is now "vhf", and you can find the available vhf plans [here](https://api.vultr.com/v2/plans?type=vhf). 

Just swap out the plan for a v2 plan name and you should be good to go

```
resource "vultr_instance" "website_instance" {
    plan = "vhf-1c-1gb"
    region = "sjc"
    os_id = "387"
    hostname = "website"
    label = "website"
}
```

**Comment by evanrich** [comment]
@mamclaughlin  thanks!  will the documentation for the provider be updated to reflect this?  Thanks!

edit:  the link you provided is much more helpful than the terraform provider docs I found via google.
