### ISSUE TITLE
[BUG] - Connectivity to API

### ISSUE THREAD

**Issue by ianbruton** [vultr/terraform-provider-vultr#101]
**Describe the bug**
when trying to run terraform from github actions, everything works fine up until apply, then it times out (see screenshot)

everything seems to be set up correctly for terraform, it just doesn't seem to be getting access to my vultr account. I have tried running it on a github hosted runner also, but I am currently running the github runner client on a vultr host in my own account. I have whitelisted the IP address of the host (it's a reserved IP address) in the API settings of my vultr account. I have verified on the host that the vultr API key is getting set correctly in the provider definition. 

**To Reproduce**
1. use terraform cloud workspace for state
2. use github actions
3. set vultr api key in tf provider 
4. setup github runner to run on vultr host in own account
5. run actions pipeline 

**Expected behavior**
resoiurces get created

**Screenshots**
![image](https://user-images.githubusercontent.com/4050482/102724270-b4643000-430e-11eb-8596-800d35d91d5b.png)

**Desktop (please complete the following information where applicable:**
 - Runner OS: ubuntu 18.04 
 - Provider Version 2.1.1

**Additional context**
- using a high frequency host type

**Comment by ddymko** [comment]
@ianbruton This looks like an issue with the vultr-provider being able to connect to the API. This seems to be more of an issue with connectivity with the GitHub Action (configuration). The terraform provider may not be getting the API key or is unable to call to the Vultr API

**Comment by ddymko** [comment]
Are you able to run this terraform plan locally on your machine? Not entirely sure what the issue could be here apart from configuration on the CI causing issues.

**Comment by ianbruton** [comment]
I am running it in github actions, which is running it on a vultr server in my vultr account. The plan is successful, just not the apply

![image](https://user-images.githubusercontent.com/4050482/102725239-a49c1a00-4315-11eb-8876-74f0aecf4a61.png)

**Comment by ianbruton** [comment]
so the runner is already inside the vultr network

**Comment by ianbruton** [comment]
a few more things that I have tried
- allowing any ipv4 address to use the api key. 
- recreated the workspace in tf cloud
- ensured workspace was set to local deployments (plan and apply run on my server, not theirs)
- double checked all the tokens are the correct ones
- double checked the github config

the error never changed

I tried to have a look in other vultr account settings and server settings but I cannot seem to fine the root cause.

The state file is getting updated, the backend is establishing, plan is being made, just always fails on apply

**Comment by ddymko** [comment]
Thanks for the testing info.

The only suggestion I can think of right now is bumping the retry limits to something a bit higher such as 

```
provider "vultr" {
  api_key = "VULTR_API_KEY"
  rate_limit = 1300
  retry_limit = 6
}
```

**Comment by ianbruton** [comment]
Just gave this a shot, no luck

**Comment by ddymko** [comment]
Could you share your entire TF plan? Maybe this can shed some light as to why this is failing for you

**Comment by ianbruton** [comment]
![image](https://user-images.githubusercontent.com/4050482/102814576-25691d80-43cb-11eb-8943-11b2d3ceedcb.png)

**Comment by ianbruton** [comment]
apologies for the formatting

**Comment by ddymko** [comment]
could you provide the `.tf` file so I can copy it and run it myself?

**Comment by ianbruton** [comment]
terraform {
  backend "remote" {
    organization = "brewton-ind"
    workspaces {
      name = "pt-mgmt"
    }
  }

  required_providers {
    vultr = {
      source = "vultr/vultr"
      version = "2.1.1"
    }
  }
}

data "local_file" "vultr_api_key" {
    filename = "keys/VULTR_API_KEY"
    # filename = "${path.module}/foo.bar"
}

provider "vultr" {
  api_key = data.local_file.vultr_api_key.content
  rate_limit = 1300
  retry_limit = 6
}

data "local_file" "pt_key" {
    filename = "keys/PT_KEY"
    # filename = "${path.module}/foo.bar"
}

resource "vultr_ssh_key" "pt_hf" {
  name = "pt-key"
  ssh_key = data.local_file.pt_key.content
}

resource "vultr_reserved_ip" "pt_ip_001" {
  label = "pt_ip_001"
  region = "sea"
  ip_type = "v4"
}

resource "vultr_firewall_group" "pt_group" {
    description = "pt-firewall"
}

variable "home_ip_address" {
    type = string
    default = "1.2.3.4"
}

resource "vultr_firewall_rule" "ssh_rule_definition" {
    firewall_group_id = vultr_firewall_group.pt_group.id
    protocol = "tcp"
    ip_type = "v4"
    subnet = var.home_ip_address
    subnet_size = 32
    port = 22
}

**Comment by ianbruton** [comment]
It is not all in one file in my project, but I don't think it would matter, I put it all in one file here for the sake of simplicity

**Comment by ianbruton** [comment]
Also, I have tried manually performing an api call with my token on the runner host, and it works as expected, so the server has access to the API

**Comment by ddymko** [comment]
Thanks, I'll try to dig into this for you

**Comment by ianbruton** [comment]
if you need any more info just let me know, I am free to share my screen on a call even if that helps (not sure if that is something you guys do) Just let me know.

**Comment by ianbruton** [comment]
also, thank you very much for taking the time

**Comment by ianbruton** [comment]
Hi, did you have any look digging into this at all?

**Comment by ddymko** [comment]
@ianbruton I can not find the root cause as to why your github actions are failing. 

If you are able to make API calls locally with your API key then this leads me to believe there is something wrong with the runners.

The only other place where the API might cause issues is in the allow/deny list for IPv4 and IPv6 addresses
https://my.vultr.com/settings/#settingsapi
