### ISSUE TITLE
[BUG] - docs of instance_ipv4 are unclear

### ISSUE THREAD

**Issue by x70b1** [vultr/terraform-provider-vultr#104]
**Describe the bug**
I looked at the [Resources/instance_ipv4](https://github.com/vultr/terraform-provider-vultr/blob/master/website/docs/d/instance_ipv4.html.markdown
) docs.

For me it looks like a copy of `vultr_reverse_ipv4`. I guess the work is not finished on that page? Header and content are similar.
Also its not clear what `instance_ipv4` should do. I think it should add a new ipv4 address to the server.  

**To Reproduce**

1. Go to [Resources/instance_ipv4](https://github.com/vultr/terraform-provider-vultr/blob/master/website/docs/d/instance_ipv4.html.markdown
)
2. See error
3. ...
4. Profit

**Expected behavior**

I should lookt at a beautiful terraform doc.

**Comment by ddymko** [comment]
@x70b1 `instance_ipv4` lets you attached another (or multiple) IPv4 address to your instance.

Both instance ipv4 and reverse ipv4 will return similar data but the docs have typos in them. We will update the docs to clear up the confusion

**Comment by x70b1** [comment]
Awesome, thanks! :heart:
