### ISSUE TITLE
Argument Reference - name - (Required) Name (subdomain) for this record.

### ISSUE THREAD

**Issue by dR3b** [vultr/terraform-provider-vultr#105]
I cannot create a CAA entry because the "name" field is mandatory:
```bash
    4 resource "vultr_dns_domain" "DOMAIN" {
    5   domain = "DOMAIN"
    6   ip     = "X.X.X.X"
    7 }

   25 resource "vultr_dns_record" "letsencrypt" {
   26   domain = vultr_dns_domain.DOMAIN.id
   27   data   = "0 issue \"letsencrypt.org\""
   28   name   = ""
   29   type   = "CAA"
   30   ttl    = 1800
   31 }
```
But it is not. What am I doing wrong?

https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/dns_record

**Comment by ddymko** [comment]
@dR3b The TF you have is valid but there is an issue with the Go client this provider is using to interact with Vultr. 

It is omitting the `""` in the request to the Vultr API - we will update govultr to allow `""` in the requests and then update the dependency on TF which will fix this issue.

**Comment by dR3b** [comment]
Thank you!
