### ISSUE TITLE
Error when creating instance from snapshot

### ISSUE THREAD

**Issue by iggy** [vultr/terraform-provider-vultr#11]
The error I'm seeing:

```
Error: Error while waiting for Server $ID to be in a active state : unexpected state '', wanted target 'running'. last error: %!s(<nil>)
```

I think the process for creating an instance from a snapshot goes through some different stages than from a normal instance creation.

It looks like the state ends up being `''` at which point, I think the provider should send a restart request to the instance and then wait for the state to be running.

I've historically been able to catch the instance and hit restart in the vultr website in time to have the provider work. Either I'm too slow lately or something has changed in the provider or in the API to make that no longer work.

If I create an instance from a snapshot in the website, I have to restart it before it's usable. I'm not sure if that's expected, but it's always been that way.

Please let me know what other information I can provide. I'm sure I'm forgetting some (probably key) piece of information.

**Comment by ddymko** [comment]
Hey @iggy 

This strikes me as odd even since you have to restart the box on the web UI. I am going to look into this for you and get back to you. This may be a bug that has gone unnoticed so I will dig into the API and see what is going on here.

**Comment by ddymko** [comment]
@iggy 

I couldn't replicate your specific issue. I created the following resource which has a basic snapshot of a 1-click lamp app we have

```hcl
resource "vultr_server" "my_server" {
    plan_id = "401"
    region_id = "6"
    snapshot_id = "1de5de7d9629a"
    label = "my-server-label"
    tag = "my-server-tag"
    hostname = "my-server-hostname"  
}
```

During the apply process the server gets blocked until it is in the proper state

```
vultr_server.my_server: Creating...
vultr_server.my_server: Still creating... [10s elapsed]
vultr_server.my_server: Still creating... [20s elapsed]
vultr_server.my_server: Still creating... [30s elapsed]
vultr_server.my_server: Still creating... [40s elapsed]
vultr_server.my_server: Still creating... [50s elapsed]
vultr_server.my_server: Still creating... [1m0s elapsed]
vultr_server.my_server: Still creating... [1m10s elapsed]
vultr_server.my_server: Still creating... [1m20s elapsed]
vultr_server.my_server: Still creating... [1m30s elapsed]
vultr_server.my_server: Still creating... [1m40s elapsed]
vultr_server.my_server: Still creating... [1m50s elapsed]
vultr_server.my_server: Still creating... [2m0s elapsed]
vultr_server.my_server: Still creating... [2m10s elapsed]
vultr_server.my_server: Still creating... [2m20s elapsed]
vultr_server.my_server: Still creating... [2m30s elapsed]
vultr_server.my_server: Still creating... [2m40s elapsed]
vultr_server.my_server: Still creating... [2m50s elapsed]
vultr_server.my_server: Still creating... [3m0s elapsed]
vultr_server.my_server: Still creating... [3m10s elapsed]
vultr_server.my_server: Still creating... [3m20s elapsed]
vultr_server.my_server: Still creating... [3m30s elapsed]
vultr_server.my_server: Still creating... [3m40s elapsed]
vultr_server.my_server: Still creating... [3m50s elapsed]
vultr_server.my_server: Still creating... [4m0s elapsed]
vultr_server.my_server: Still creating... [4m10s elapsed]
vultr_server.my_server: Still creating... [4m20s elapsed]
vultr_server.my_server: Still creating... [4m30s elapsed]
vultr_server.my_server: Still creating... [4m40s elapsed]
vultr_server.my_server: Creation complete after 4m42s [id=31749701]
```

I also tried doing this on my.vultr.com. The state is pending until the snapshot is fully provisioned. Then once it is in an active state I am able to take the supplied IP address and hit the instance without any issues.

Also setup terraform to pull from a datasource without any issues as well

```hcl
data "vultr_snapshot" "my_snapshot" {
  filter {
    name = "description"
    values = ["tf-issue"]
  }
}

resource "vultr_server" "my_server" {
    plan_id = "401"
    region_id = "6"
    snapshot_id = data.vultr_snapshot.my_snapshot.id
    label = "my-server-label"
    tag = "my-server-tag"
    hostname = "my-server-hostname"  
}
```


Are you using a preexisting snapshot? Also what type of instance are you deploying and the region?

**Comment by iggy** [comment]
I created a snapshot of an alpine instance I created from the iso library functionality. The snapshot was created in May. It may also help to know, the instance has a btrfs root, so some of the Vultr tooling to set passwords/etc may not work properly.

The original instance (that the snapshot was created from) was a $5/mo plan (201). The one I'm creating now is also a $5/mo plan (201).

The snapshot is in Dallas, and the instance I'm creating is in Dallas as well.

**Comment by ddymko** [comment]
@iggy 

Thanks for sharing! Since this has always been an issue for you we are going to look into the core of snapshot within Vultr. This way we can resolve the issue at the root.

**Comment by iggy** [comment]
Okay. Do you need the snapshot ID? A vultr ticket from my account? etc?

**Comment by ddymko** [comment]
@iggy 

Do you already have an existing ticket for this? If you don't you can create one regarding how snapshots are behaving for you (need to restart etc).

**Comment by iggy** [comment]
Ticket #UHS-08GYW
