### ISSUE TITLE
[BUG] - snapshot_id isn't a valid UUID

### ISSUE THREAD

**Issue by EuAndreh** [vultr/terraform-provider-vultr#110]
**Describe the bug**

Using `snapshot_id` on a `vultr_instance` gives a 400 API response with the message `Invalid UUID format.`.

I couldn't find a better identifier value for the snapshot to replace it with. The same `snapshot_id` worked with version 1.5.0, so I guess this is related to the 1.5.0 -> 2.1.2 version upgrade.

**To Reproduce**

Working declaration:

```hcl
terraform {
  required_providers {
    vultr = {
      source  = "vultr/vultr"
      version = "~> 2.1.2"
    }
  }
  required_version = ">= 0.13"
}

variable "vultr_api_key" {
  type        = string
  description = "Vultr API key."
}

provider "vultr" {
  api_key = var.vultr_api_key
}

resource "vultr_instance" "vps_server" {
  plan = "vc2-1c-1gb"
  region = "cdg"
  os_id = "387"
}
```

Troublesome declaration:
```hcl
terraform {
  required_providers {
    vultr = {
      source  = "vultr/vultr"
      version = "~> 2.1.2"
    }
  }
  required_version = ">= 0.13"
}

variable "vultr_api_key" {
  type        = string
  description = "Vultr API key."
}

provider "vultr" {
  api_key = var.vultr_api_key
}

resource "vultr_instance" "vps_server" {
  plan = "vc2-1c-1gb"
  region = "cdg"
  snapshot_id = "5c35fb3a74873"
}
```

Console output:
```
$ terraform apply
...
vultr_instance.vps_server: Creating...

Error: error creating server: {"error":"Invalid UUID format.","status":400}

  on vps.tf line 20, in resource "vultr_instance" "vps_server":
  20: resource "vultr_instance" "vps_server" {
$ terraform --version
Terraform v0.14.4
+ provider registry.terraform.io/vultr/vultr v2.1.2
```

**Comment by EuAndreh** [comment]
I was able to get the UUID behind the previous `snapshot_id`:

```shell
$ curl -H "Authorization: Bearer $TF_VAR_vultr_api_key" https://api.vultr.com/v2/snapshots
```

This is undocumented, though.

Also: the way to correlate the `snapshot_id` with the UUID was by the `description` field. The new UUID isn't tied to the previous `snapshot_id`. It worked for me, but may be a bigger issue for someone else.

**Comment by EuAndreh** [comment]
> This is undocumented, though.

Well, this is not actually true. It is documented on https://www.vultr.com/api/v2/#operation/list-snapshots

I got frustrated with getting stuck on this, and as is was non-obvious I exaggerated towards undocumented.

A fairer description would be non-obvious, or a bit hidden.

**Comment by jsuchan-reef** [comment]
This is the only result for keyword `Invalid UUID format.` + `Vultr` + `Terraform`, so in case someone would stumble upon the same error but with different circumstances - in my case I was using a wrong ID for ssh key where UUID format is also expected.
