### ISSUE TITLE
[Feature] - Ability to change user_data without instance replace

### ISSUE THREAD

**Issue by filipetoscano** [vultr/terraform-provider-vultr#115]
**Is your feature request related to a problem? Please describe.**
Changing the `user_data` field in a `vultr_instance` resource forces an instance replacement, as seen in the screenshot below:

![image](https://user-images.githubusercontent.com/290602/108071781-0c44bc00-705e-11eb-8600-9a7a70879bee.png)

Note: We're currently using `user_data` as a replacement for generic key/value tuples (ie, labels) that are available in other cloud providers.

**Describe the solution you'd like**
Changing the `user_data` field should cause the instance to be updated in-place, like how updating the `tag` attribute works:

![image](https://user-images.githubusercontent.com/290602/108071260-6e50f180-705d-11eb-84a2-6cceb447c44e.png)

**Describe alternatives you've considered**
* Adding a fake `labels` attribute to the terraform configuration file, but commenting out;
* Once terraform completes, run an additional script to extract this information;

```
resource "vultr_instance" "na-10-000" {
  hostname = "na-10-000"
  label = "na-10-000"
//labels = {
//   region = "eu"
//   dc = "eu-central"
//   "consul/server" = ""
//   "nomad/server" = ""
//   "vault/server" = ""
//   "nomad/group" = "hq"
//}

  region = "ewr"
  plan = "vc2-1c-1gb"
```

**Comment by ddymko** [comment]
@filipetoscano 

Thanks for creating the ticket but this isn't something we will implement. Originally the `user_data` behavior was not to replace upon changes however with https://github.com/vultr/terraform-provider-vultr/issues/69  https://github.com/vultr/terraform-provider-vultr/issues/70 we changed this so that any changes to user-data would replace the instance.

**Comment by filipetoscano** [comment]
Hi @ddymko

Ok, fair enough if somebody else is already depending on a specific behavior (ie, to force their instance to be reconfigured). I assume that I could "repurpose" this field based on the documentation.

As per https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/instance#tag:
Generic data store, which some provisioning tools and cloud operating systems use as a configuration file. It is generally consumed only once after an instance has been launched, but individual needs may vary.

Are you considering adding an additional `Map<string,string>` attribute that we could use for our custom metadata purposes?

**Comment by ddymko** [comment]
@filipetoscano 

Adding in a new field isn't something we are considering at the moment.

One solution you could possible use is passing in a URL to the user-data which would contain your metadata. 
An example would be storing your K/V in a object storage bucket and passing that URL to your instances. This would then allow you to update and configure your metadata separately from your instance
