### ISSUE TITLE
[BUG] - Issue adding DNS TXT record for Mail Delivery

### ISSUE THREAD

**Issue by siffland** [vultr/terraform-provider-vultr#117]
**Describe the bug**
Attempting to add a TXT DNS record to vultr for spf mail record (as described by fastmail, and i can enter this manually on vultr's website as a record).  Applying the code gives the following error:

```
vultr_dns_record.spf: Creating...

Error: error creating DNS record : {"error":"Unable to add record: Record data must be enclosed in quotes","status":400}
```

**To Reproduce**
Resource in my tf file
```
resource "vultr_dns_record" "spf" {
    type = "TXT"
    domain = vultr_dns_domain.example_org.id
    name = ""
    data = "v=spf1 include:spf.messagingengine.com ?all"
    ttl = var.DNSTTL
}
```
Terraform apply results
```
Terraform will perform the following actions:

  # vultr_dns_record.spf will be created
  + resource "vultr_dns_record" "spf" {
      + data   = "v=spf1 include:spf.messagingengine.com ?all"
      + domain = "example.org"
      + id     = (known after apply)
      + ttl    = 3600
      + type   = "TXT"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vultr_dns_record.spf: Creating...

Error: error creating DNS record : {"error":"Unable to add record: Record data must be enclosed in quotes","status":400}
```

**Expected behavior**
Expected a TXT record to be created with the proper data

**Desktop (please complete the following information where applicable:**
- Terraform Version - Terraform v0.13.4
- vultr plugin - vultr v2.1.3

**Comment by siffland** [comment]
I guess this isn't a bug, I was able to add the TXT record with the following code below.  If this is the expected behavior this ticket can be closed.

```
resource "vultr_dns_record" "spf" {
    type = "TXT"
    domain = vultr_dns_domain.example_org.id
    name = ""
    data = "\"v=spf1 include:spf.messagingengine.com ?all\""
    ttl = var.DNSTTL
}
```

**Comment by ddymko** [comment]
@siffland This is expected behavior as the API didn't enclose the string you supplied. However we are making an update to the API which will wrap the supplied `data` in quotes so you won't have to escape them

**Comment by blisscs** [comment]
I am facing similar issues that I have to escape the values for the `TXT` type.

I am wondering is this feature already included?
