### ISSUE TITLE
[Feature] - Support setting backup schedule during instance creation

### ISSUE THREAD

**Issue by crouthamela** [vultr/terraform-provider-vultr#119]
**Is your feature request related to a problem? Please describe.**
When creating an instance, it would be great to set the backup schedule at the same time.

**Describe the solution you'd like**
An argument or series of arguments for vultr_instance related to backup configuration to match the v2 API: https://www.vultr.com/api/#operation/create-instance-backup-schedule

**Comment by grant-veepshosting** [comment]
+1 for this feature, would be amazing. Happy to help out wherever possible, testing, feedback, etc.

**Comment by ddymko** [comment]
@crouthamela @grant-veepshosting 

I think the best approach here would be to create a `resource_vultr_backup`. We have some pending changes that would have to go out in a new release, v2.3.0, so we'll work on getting this new resource packed for that version. 

I would say targeted release for v2.3.0 would be middle/late next week.

**Comment by grant-veepshosting** [comment]
Thanks for the fast turnaround on an update and expected next steps @ddymko .
A related request, albeit much more minor: on 'vultr_instance::instance::backups' parameter, can this be converted to a Boolean? Previously tested with this value set to "true" which failed silently (no backups on created resource), then found the correct value was "enabled" instead. Could also accept "yes", "1", etc...

**Comment by ddymko** [comment]
@grant-veepshosting I don't want to deviate TF, GoVultr, and the API too much with their respective fields and don't want to introduce a breaking change if it can be avoided. 

What we can do here is two things 

1. Have TF validate and only accept  `enabled` or `disabled` as valid fields. 
2. Update the API to also have better validation of this field since if you are passing in garbage strings it should reject that.

**Comment by crouthamela** [comment]
Great news, thanks for developing this!

**Comment by grant-veepshosting** [comment]
> @grant-veepshosting I don't want to deviate TF, GoVultr, and the API too much with their respective fields and don't want to introduce a breaking change if it can be avoided.
> 
> What we can do here is two things
> 
>     1. Have TF validate and only accept  `enabled` or `disabled` as valid fields.
> 
>     2. Update the API to also have better validation of this field since if you are passing in garbage strings it should reject that.

Both recommendations make sense. 1. so it errors instead of failing silently; and 2. In case of any other automation tooling making a similar mistake.

**Comment by ddymko** [comment]
quick update - the API has been updated to rejected requests if backups aren't `disabled` or `enabled`

**Comment by ddymko** [comment]
@crouthamela @grant-veepshosting 

Had to change from the original proposal of having a separate `backups_schedule` resource. This would have caused a few issues with how we handle state.

The way it is implemented now will be part of the instance resource 

```hcl
resource "vultr_instance" "my_instance" {
    plan = "vc2-1c-1gb"
    region = "sea"
    os_id = "167"
    backups = "enabled"
    backups_schedule {
      type = "daily"
      hour = 6
    }
}
```

If `backups` are set to enabled then `backups_schedule` needs to be be defined.

**Comment by ddymko** [comment]
Just an update.

We planned on doing a new TF release for the backups today. However we have just released new updates to our load balancers (private networks and firewalls). So we decided to push back the release to next week. This way we can package all of the updates from backups, load balancers, and various others we have staged in a single release.

**Comment by ddymko** [comment]
Hey all,

We just released v2.3.0 which has the `backups_schedule` support. I'll keep this ticket open for a bit longer in case any questions pop up we can use this thread.

**Comment by crouthamela** [comment]
Thank you!


________________________________

**Comment by grant-veepshosting** [comment]
Works like a charm!
