### ISSUE TITLE
[Feature] - Support for darwin_arm64

### ISSUE THREAD

**Issue by lcmartinezdev** [vultr/terraform-provider-vultr#124]
I tried to use this provider with my Macbook Pro Apple M1  then I got this error:

Error: Incompatible provider version

Provider registry.terraform.io/vultr/vultr v2.1.4 does not have a package
available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.

**Comment by ddymko** [comment]
@lcmartinezdev thanks for creating the issue.

I'll look into seeing what is required for us to have the Terraform registry hand off m1 binaries

**Comment by ddymko** [comment]
@lcmartinezdev

We had bumped the provider to build _drawin_arm64_ in the latest release: https://github.com/vultr/terraform-provider-vultr/releases/tag/v2.2.0

**Comment by lcmartinezdev** [comment]
So fast!
Thank you!
@ddymko
