### ISSUE TITLE
Bad error message

### ISSUE THREAD

**Issue by johnrichardrinehart** [vultr/terraform-provider-vultr#127]
https://github.com/vultr/terraform-provider-vultr/blob/495ed5febc181da59bad097c2f59e15b95e1b4e3/vultr/resource_vultr_instance.go#L436

Should the error message read "error attaching" not "error detaching"?

**Comment by ddymko** [comment]
@johnrichardrinehart yeah, the message should say `error attaching` since the call is for `client.Instance.AttachISO`

**Comment by johnrichardrinehart** [comment]
Submitted #129 .
