### ISSUE TITLE
Enable private networking via Terraform

### ISSUE THREAD

**Issue by v0112358** [vultr/terraform-provider-vultr#13]
Hi, While creating private networks I got the following error message:

```
Error: Error creating network: Not currently enabled on your account, enable on https://my.vultr.com/networks/
```
My tf code:
```
resource "vultr_network" "network-prod-vultr-private-network" {
  count       = 2
  cidr_block  = cidrsubnet("10.192.0.0/23", 1, count.index)
  description = "Singapore private network for production env"
  region_id   = data.vultr_region.singapore.id
}
```
If I enable multiple private networks via Vultr console, tf apply is work fine as expected. I think that terraform-provider-vultr should be allowed to enable multiple private networks via Terraform (I couldn't find the resource for enable multiple private networks).

**Comment by ddymko** [comment]
Hey @mrmainnet 

The API doesn't support the ability to enable multiple private networks through the API. (referring to the advance section of https://my.vultr.com/networks/). 

To allow this we would have to update the core API to make this possible. We are in the early stages of designing a V2 of the API and allowing to enable/disable multiple private networks would be a welcome addition!

**Comment by derrickmehaffy** [comment]
Not sure if it's related but I can't even enable a network resource per: https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/network

```
resource "vultr_network" "strapi_network" {
  description = var.network_desc
  region = var.region
  subnet  = var.network_subnet
  subnet_size = var.network_subnet_size
}
```

Error

```
Error: Invalid resource type

  on main.tf line 21, in resource "vultr_network" "strapi_network":
  21: resource "vultr_network" "strapi_network" {

The provider provider.vultr does not support resource type "vultr_network".
```

**Comment by ddymko** [comment]
@derrickmehaffy The docs for v2 are wrong. The resource is `vultr_private_network`. We merged in a patch for this today #87

**Comment by derrickmehaffy** [comment]
Ah Thanks @ddymko was wondering what was going on, think I have a little work around to declare the `enable_private_network` on once instance, and declare the ids on the others.

**Comment by ddymko** [comment]
Closing this as `Error: Error creating network: Not currently enabled on your account, enable on https://my.vultr.com/networks/` is no longer a behavior on Vultr. There are just `private networks` on your account don't need to enable anything anymore.
