### ISSUE TITLE
[BUG] - Please upload select a valid ISO or specify a valid iPXE Chain URL

### ISSUE THREAD

**Issue by amjanoni** [vultr/terraform-provider-vultr#132]
**Describe the bug**
The message Please upload select a valid ISO or specify a valid iPXE Chain URL appears when I try to create an Instance using the PXE startup script, the ID that the vultr_startup_script brings appears to be not valid if I check the payload in browser I see another type of ID being passed to Vault API.

**To Reproduce**

```terraform
resource "vultr_startup_script" "my_script" {
    name = "man_run_docs"
    script = base64encode("echo $PATH")
    type = "pxe"
}

resource "vultr_instance" "main" {
  plan             = vc2-1c-1gb
  region           = sea
  os_id            = 159
  script_id        = vultr_startup_script.my_script.id
}
```

If you check the request when creating the VM using the Vultr Portal you can see a different ID being used, when I use this ID in the script_id it works.

![image](https://user-images.githubusercontent.com/70039618/116504234-38668f80-a88e-11eb-9706-4c4e8ebfc350.png)

**Expected behavior**
VM should create correctly when using PXE startup scripts.

**Screenshots**
![image](https://user-images.githubusercontent.com/70039618/116503564-d194a680-a88c-11eb-9bcb-e5bb4154f9a6.png)

**Additional context**

I check the Vultr API and looks the ID that works correctly is from the API v1,
https://www.vultr.com/api/v1/#startupscript

**Comment by ddymko** [comment]
@amjanoni Thanks for creating the ticket. We'll look into this.

**Comment by ddymko** [comment]
@amjanoni There was an issue with the API which we have patched. I just copied and pasted your .tf file and it ran fine.


Would you mind trying again?

**Comment by amjanoni** [comment]
> @amjanoni There was an issue with the API which we have patched. I just copied and pasted your .tf file and it ran fine.
> 
> Would you mind trying again?

It's working now, thanks you!

**Comment by amjanoni** [comment]
> @amjanoni There was an issue with the API which we have patched. I just copied and pasted your .tf file and it ran fine.
> 
> Would you mind trying again?
