### ISSUE TITLE
[Feature] - In place plan upgrade

### ISSUE THREAD

**Issue by grant-veepshosting** [vultr/terraform-provider-vultr#139]
Via the web interface, in-place upgrades are possible to higher level plans, where capacity exists to support this.
Currently when trying to change the plan via the Terraform code, it will attempt to delete and re-create the instance instead.
Is it possible in place upgrades can be supported via API and Terraform, where capacity exists, to match the web interface functionality?

**Comment by ddymko** [comment]
@grant-veepshosting The API already supports this within the `update instance` call https://www.vultr.com/api/#operation/update-instance by supplying a new plan it will`Upgrade the instance with this Plan id.`

As for terraform I believe this is something we can do. I'll spend some time looking into this and see what will be the best way forward.

**Comment by ddymko** [comment]
@grant-veepshosting Just pushed up a draft PR that removes the `force_new` on plan changes and allows inplace upgrades. We are going test this a bit more and look at a few other options. If you want to test it out yourself and if you have any feedback let me know.

**Comment by grant-veepshosting** [comment]
@ddymko can we re-open this one please?

We have done some testing, and although the upgrade works as expected it does not update the data in the Terraform state information, meaning subsequent 'terraform plan' operations fail or try to repeat the upgrade action.

Examples of values not upgraded include plan, bandwidth, memory, etc.

**Comment by ddymko** [comment]
@grant-veepshosting I am not sure why the state isn't updating.

After the update call finishes the read call should go through and update all of the values but for some reason that isn't happening.

If I force a read `terraform refresh` it gets the data without issue. I'll look into this.

**Comment by ddymko** [comment]
There is a delay in the API responses that is causing drift - I'll work on getting this fixed .

**Comment by ddymko** [comment]
@grant-veepshosting We had to add in a custom wait for upgrade plans...the API delays the response. Which is why we didn't notice the 1st time around. I'll be cutting a release with these changes today/tomorrow.

If anything else comes up let me know!
