### ISSUE TITLE
[BUG] - Importing vultr_bare_metal_server resource forces replacement due to enable_ipv6

### ISSUE THREAD

**Issue by tmickel** [vultr/terraform-provider-vultr#156]
**Describe the bug**
Hello. I'm a new Vultr customer and created a bare metal resource in the web panel yesterday. Today I tried to import it into a new Terraform configuration, but Terraform wants to force replacement of the server due to what looks like a bug. Is there any way to work around this?

**To Reproduce**
1. Created a bare metal server in the web panel, with IPv6 enabled
2. Added a terraform resource with the following matching configuration:
```tf
resource "vultr_bare_metal_server" "prod-1" {
  plan = "vbm-4c-32gb"
  region = "ewr"
  os_id = 352
  label="prod-1"
  enable_ipv6 = true
}
```
3. Imported the resource into Terraform state: `terraform import vultr_bare_metal_server.prod-1 [server ID from control panel URL]` ... `Import successful!`
4. `terraform plan` shows that the resource must be recreated due to the ipv6 flag:
```tf
Terraform will perform the following actions:

  # vultr_bare_metal_server.prod-1 must be replaced
-/+ resource "vultr_bare_metal_server" "prod-1" {
      + activation_email = true
      ~ app_id           = 0 -> (known after apply)
      ~ cpu_count        = 4 -> (known after apply)
      ~ date_created     = "2021-07-28T15:51:36+00:00" -> (known after apply)
      + default_password = (sensitive value)
      ~ disk             = "2x 240GB SSD" -> (known after apply)
      + enable_ipv6      = true # forces replacement
      ~ gateway_v4       = "[redacted]" -> (known after apply)
      ~ id               = "[redacted]" -> (known after apply)
      - label            = "prod-1" -> null
      ~ mac_address      = [redacted] -> (known after apply)
      ~ main_ip          = [redacted] -> (known after apply)
      ~ netmask_v4       = [redacted] -> (known after apply)
      ~ os               = "Debian 10 x64 (buster)" -> (known after apply)
      ~ ram              = "32768 MB" -> (known after apply)
      + reserved_ipv4    = (known after apply)
      ~ status           = "active" -> (known after apply)
      + user_data        = (known after apply)
      ~ v6_main_ip       = [redacted] -> (known after apply)
      ~ v6_network       = [redacted] -> (known after apply)
      ~ v6_network_size  = 64 -> (known after apply)
        # (3 unchanged attributes hidden)
    }
```
5. **Changing `enable_ipv6` to false, or deleting the line altogether, from the configuration still forces replacement.**

**Expected behavior**
I can import an IPv6-enabled bare metal server without a forced replacement.

**Screenshots**
N/a, happy to add more, let me know

**Desktop (please complete the following information where applicable:**
 - OS: Linux (Debian)

**Additional context**
Thanks!

**Comment by ddymko** [comment]
@tmickel thanks for letting us know.

We'll look into this and see whats going on

**Comment by ddymko** [comment]
released in https://github.com/vultr/terraform-provider-vultr/releases/tag/v2.4.0

**Comment by tmickel** [comment]
Thanks for the fast turnaround!
