### ISSUE TITLE
cloudinit not working

### ISSUE THREAD

**Issue by derust** [vultr/terraform-provider-vultr#170]
can cloudinit works like aws ec2?

[Provision Infrastructure with Cloud-Init](https://learn.hashicorp.com/tutorials/terraform/cloud-init?in=onboarding/tfcb-week-6)

I try this tutorial use vultr provider, but it just spawn the instance, cloudinit haven't run.

**Comment by ddymko** [comment]
@derust 

Not all of our images support cloud-init at the moment. 

Here is a list of which images currently have cloud-init support : https://www.vultr.com/docs/getting-started-with-cloud-init

We are working towards updating all of the images to have cloud-init
