### ISSUE TITLE
[BUG] data "vultr_account" incorrect types

### ISSUE THREAD

**Issue by 4n70w4** [vultr/terraform-provider-vultr#171]
**Describe the bug**
I get rounded values of `balance` and `pending_charges` but vultr returns its as floats.

**To Reproduce**

```tf
data "vultr_account" "my_account" {}

output "my_account_balance" {
  value = data.vultr_account.my_account.balance
}

output "my_account_pending_charges" {
  value = data.vultr_account.my_account.pending_charges
}
```

```bash
terraform apply
```

```bash
my_account_balance = -8
my_account_pending_charges = 0
```

But `GET https://api.vultr.com/v2/account` returns:

```json
{"account":{"balance":-8.52,"pending_charges":0.04,.......}}
```

**Expected behavior**
Get float values of `balance` and `pending_charges`.

**Desktop (please complete the following information where applicable:**
```
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/vultr/vultr v2.5.0
```

**Comment by ddymko** [comment]
@4n70w4 

Thanks for reporting the issue. The API does return them as floats and it looks like TF has them set as INTs. We'll patch this up

**Comment by 4n70w4** [comment]
@ddymko May be need make release? I don't see changes =(

**Comment by ddymko** [comment]
@4n70w4 we are planning a release for this upcoming week. We have other updates we are going to package together.
