### ISSUE TITLE
[BUG] - Error: error getting instance

### ISSUE THREAD

**Issue by chipxen** [vultr/terraform-provider-vultr#177]
**Describe the bug**
After manually deleting the instance in my account I have an error:

```
│ Error: error getting instance (cdb7b70d-4c61-47dc-8028-a0f9e88e1715): {"error":"invalid instance ID","status":400}
│
│   with module.vultr_servers_icn.vultr_instance.tf-server[0],
│   on .terraform/modules/vultr_servers_icn/main.tf line 9, in resource "vultr_instance" "tf-server":
│    9: resource "vultr_instance" "tf-server" {
```

**To Reproduce**
1. From terraform create instance: terraform apply
2. Go to https://my.vultr.com/ and click "Server destroy"
3. Back to terraform and run terraform plan or terraform apply 

**Expected behavior**
Create a new server.

**Comment by ddymko** [comment]
@chipxen thanks for letting us know.

We'll look into this

**Comment by ddymko** [comment]
@chipxen I submitted a fix for this issue. 

We will release this as part of a larger release with other changes we have. We are aiming to have that release cut by the end of this week

**Comment by CHIP0K** [comment]
> @chipxen I submitted a fix for this issue.
> 
> We will release this as part of a larger release with other changes we have. We are aiming to have that release cut by the end of this week

thnx)
