### ISSUE TITLE
Add the ability to set reverse DNS entries for IPv4 and IPv6 addresses

### ISSUE THREAD

**Issue by bovarysme** [vultr/terraform-provider-vultr#18]
Hello,

Thank you for developing an in-house Terraform provider and working through the process to make it official! It's one of the reasons why I switched from another cloud provider.

Right now, the only feature missing for my use case is the ability to set reverse DNS entries for IPv4 and IPv6 addresses. It seems like these options are not supported by `govultr`'s `ServerOptions` struct, and would require extra API calls after server creation. Do you think it would be possible to add such a feature?

**Comment by ddymko** [comment]
Hey @bovarysme 

So the there is ability to do this via the API and in GoVultr:

https://www.vultr.com/api/#server_reverse_set_ipv4
https://www.vultr.com/api/#server_reverse_set_ipv6

https://godoc.org/github.com/vultr/govultr#ServerServiceHandler.SetReverseIPV4

So we could add this in as a feature. This may be added in as its own resource/datasource as opposed to adding it into the serverOptions.

**Comment by gszathmari** [comment]
+1
