### ISSUE TITLE
[BUG] - JSON parsing error for the monthly_cost field when requesting plans from the API.

### ISSUE THREAD

**Issue by nnhanndakara** [vultr/terraform-provider-vultr#183]
**Describe the bug**

The current provider version (2.6.0) has begun having issues parsing plans with a non-int/float value for the `monthly_cost` field.

**To Reproduce**

Create a minimal terraform module:

In `main.tf`:

```tf
terraform {
  required_providers {
    vultr = {
      source  = "vultr/vultr"
      version = ">= 2.6.0"
    }
  }
}

variable "vultr_api_key" {}

provider "vultr" {
  api_key = var.vultr_api_key
}

data "vultr_plan" "server_plan" {
  filter {
    name = "ram"
    values = [4096]
  }
  filter {
    name = "type"
    values = ["vhf"]
  }
  filter {
    name = "vcpu_count"
    values = [2]
  }
}
```

Then run `terraform init` and `terraform plan` as usual, filling in your key when requested.

**Expected behavior**

This module does nothing, so no changes should be suggested.

**Actual behavior**

The provider attempts to fetch the current list of plans (I assume using `govultr`), and fails with the following output:

```
╷
│ Error: Error getting plans: json: cannot unmarshal number 7.5 into Go struct field Plan.plans.monthly_cost of type int
│ 
│   with data.vultr_plan.server_plan,
│   on main.tf line 16, in data "vultr_plan" "server_plan":
│   16: data "vultr_plan" "server_plan" {
│ 
╵
```

Go is not a language I have a lot of experience with yet, but the field appears to be correctly declared as a float in both the provider, and `govultr`, so I'm not sure where the problem is at the moment.

**Comment by nnhanndakara** [comment]
Ahh, well that's anti-climactic. `vendor/github.com/vultr/govultr/v2` is out of date.

Edit: Just to clarify, 2.6.0 (the current release, as tagged), and the version of `govultr` bundled with it does not work with the current output of the plans API endpoint, as some plans may have non-integer/float `monthly_cost` values. I was looking at HEAD when I noticed it appeared to have been fixed already.

**Comment by ddymko** [comment]
@kaorihinata 

Thanks for creating the ticket.

You are correct that the some plans can be floats instead of int. This was introduced with the new Brazil region with the cheapest plan being `7.5`.

We already patched this in https://github.com/vultr/terraform-provider-vultr/pull/182 and will be releasing a new version of the Terraform provider tomorrow.

**Comment by nnhanndakara** [comment]
Yeah, I saw that after submitting this ticket. The new GitHub interface seems to switch you back from tag view easier than it used to, so while inspecting the release I was flipped back to HEAD and it looked like it should have been fixed.

Thanks!

**Comment by ddymko** [comment]
@kaorihinata 2.7.0 has been released
