### ISSUE TITLE
[Enhancement] - Filtering a vultr_plan on locations doesn't appear to perform a meaningful action.

### ISSUE THREAD

**Issue by nnhanndakara** [vultr/terraform-provider-vultr#184]
**Describe the bug**

Pre-sao (the location) it was possible to filter plans using a `vultr_plan` by `type`, `ram`, and `vcpu_count` to resolve human understandable values to an ID (which, per the Terraform glossary, are supposed to be opaque.) Now with sao duplicating a significant number of plans, and with the only difference in API output being the `locations` and `monthly_cost` fields, you would think that filtering on the `locations` field would at least allow you to return the desired result. However, attempting to pass, for example, `"sao"` as a filter value on a `vultr_plan` produces no results. If you can't filter by location, then it would appear that the changes brought upon by adding sao has effectively made the `vultr_plan` datasource useless, as there's no way to make a `vultr_plan` depend on a `vultr_region` if you can't filter by location, and you can't trigger an error early if a specific plan isn't available in a specific region, as you'll need to wait until you attempt to create an instance.

Please correct me if there is some alternate way I should be doing all of this, but passing around raw IDs would appear to be missing the point.

**To Reproduce**

This example tries to instantiate a `vultr_plan` datasource by filtering on the `locations` field.

In `main.tf`:

```tf
terraform {
  required_providers {
    vultr = {
      source  = "vultr/vultr"
      version = ">= 2.6.0"
    }
  }
}

variable "vultr_api_key" {}

provider "vultr" {
  api_key = var.vultr_api_key
}

data "vultr_plan" "server_plan" {
  filter {
    name = "locations"
    values = ["sao"]
  }
}
```

**Expected behavior**

As this module creates no resources, I would expect that it tells me that, and exits.

**Actual behavior**

No results are found, and the provider tells me this. It's odd, because sao definitely has plans, and even if by some bizarre twist the unmarshalled array was compared against the `values` array, there are plans that are only available to sao (the `-sc1` variants.)

```
╷
│ Error: no results were found
│ 
│   with data.vultr_plan.server_plan,
│   on main.tf line 16, in data "vultr_plan" "server_plan":
│   16: data "vultr_plan" "server_plan" {
│ 
╵
```

**Comment by ddymko** [comment]
@kaorihinata 

Thanks for creating the ticket.

Similar to the other issue...with the release of the Brazil location this has introduced some changes that we are working to resolve.

We'll look into how we can resolve the plan datasource issue

**Comment by nnhanndakara** [comment]
@ddymko

This would pre-exist the Brazil location as filters against arrays hasn't really been implemented in `vultr/data_source_vultr_common_schema.go` at all from what I can tell. Should I open a feature request and note that closing it would close this? Or should I open a feature request and close this? Not sure how you handle these types of conversions. I could also just leave this. Up to you.

**Comment by ddymko** [comment]
We can keep this ticket open

**Comment by nnhanndakara** [comment]
So, not sure if you had a solution to this in mind, but for the moment I'm using this:

```patch
diff --git a/vultr/data_source_vultr_common_schema.go b/vultr/data_source_vultr_common_schema.go
index a743455..7adf9be 100644
--- a/vultr/data_source_vultr_common_schema.go
+++ b/vultr/data_source_vultr_common_schema.go
@@ -68,15 +68,29 @@ func filterLoop(f []filter, m map[string]interface{}) bool {
 	return true
 }
 
-func valuesLoop(values []string, i interface{}) bool {
-	for _, v := range values {
-		if v == i {
+func stringArrayContains(values []string, value interface{}) bool {
+	for _, i := range values {
+		if i == value {
 			return true
 		}
 	}
 	return false
 }
 
+func valuesLoop(values []string, i interface{}) bool {
+	switch i.(type) {
+	case []interface{}:
+		for _, j := range i.([]interface{}) {
+			if stringArrayContains(values, j.(string)) {
+				return true
+			}
+		}
+		return false
+	default:
+		return stringArrayContains(values, i)
+	}
+}
+
 func dataSourceFiltersSchema() *schema.Schema {
 	return &schema.Schema{
 		Type:     schema.TypeSet,

```

Is there a desired behavior you'd like? For my purposes I just need to ensure that at least 1 value from `values` occurs in the actual field referenced by `name`, but it can be trivially rearranged to require that all values occur. Was there another project whose filter behavior you wanted to mimic? Or did you have something else in mind perhaps?

**Comment by ddymko** [comment]
@kaorihinata most of the datasources require at least a single value to be found. If more than 1 value is found we return an error saying "please refine your search".

I would say ideally we would want to match all of the criteria someone is looking for.

If you wouldn't mind could you submit a PR with these changes?

**Comment by nnhanndakara** [comment]
Sure thing. I'll swap it around to require all inputs as well.
