### ISSUE TITLE
[BUG] - can't get the plan when I create a instance

### ISSUE THREAD

**Issue by lyc0221** [vultr/terraform-provider-vultr#191]
**Describe the bug**
it can't get the plan when I create a instance

**To Reproduce**
1. Go to 'terraform plan'
2. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information where applicable:**
 - Language Version [e.g. PHP7, Go 1.12]

**Additional context**

terraform version: `1.0.11`

`terraform plan` can't get the `data.vultr_plan.this`, it was ok last month.

**Terraform Configuration Files**
data.tf
```
data "vultr_os" "this" {
  filter {
    name   = "name"
    values = ["Ubuntu 20.04 x64"]
  }
}

data "vultr_plan" "this" {
  filter {
    name   = "id"
    values = ["vc2-1c-2gb"]
  }
}
```

main.tf
```
module "vultr" {
  source            = "../../modules/vultr-instance"
  namenumber        = var.namenumber

  user              = var.user
  service           = var.service
  environment       = var.environment
  region            = var.region
  os_id             = data.vultr_os.this.id
  plan              = data.vultr_plan.this.id
  firewall_group_id = module.vultr_fw.this_firewall_id
}
```

**Panic Output**
```
Error: Error getting plans: json: cannot unmarshal number 7.5 into Go struct field Plan.plans.monthly_cost of type int

   with data.vultr_plan.this,
   on data.tf line 8, in data "vultr_plan" "this":
    8: data "vultr_plan" "this" {
```

**Comment by ddymko** [comment]
@lyc0221 

Make sure you are running on version v2.7.0+
https://github.com/vultr/terraform-provider-vultr/releases/tag/v2.7.0


This introduces a fix for a change in the API which causes issues

**Comment by lyc0221** [comment]
fixed,thanks
