### ISSUE TITLE
Terraform 1.1.4 error creating server: gave up after 4 attempts, last error unavailable (resp == nil)

### ISSUE THREAD

**Issue by denisse-dev** [vultr/terraform-provider-vultr#209]
**Describe the bug**
Hello, I'm using Terraform v1.1.4 and Vultr provider 2.9.0. When trying to deploy a Vultr instance using Terraform I keep getting the following error:

```
│ Error: error creating server: gave up after 4 attempts, last error unavailable (resp == nil)
│
│   with vultr_instance.my_instance,
│   on instances.tf line 17, in resource "vultr_instance" "my_instance":
│   17: resource "vultr_instance" "my_instance" {
```

**To Reproduce**
1. Create a new project following the [Vultr provider documentation](https://registry.terraform.io/providers/vultr/vultr/latest/docs#example-usage).
2. Execute `terraform init`
3. Execute `terraform apply`

**Desktop (please complete the following information where applicable:**
 - OS: Arch Linux
 - Terraform version: v1.1.4
 - Vultr provider version: 2.9.0

**Additional context**

I can successfully access Vultr's API from my terminal with my access token and I can deploy Vultr instances on the website so it doesn't seem to be an authentication or authorization issue.

I tried deploying in other regions and with other os id's but the issue persist.

**Comment by ddymko** [comment]
hey @da-edra do you mind supplying your full `.tf` file?

**Comment by denisse-dev** [comment]
Hi @ddymko , thanks for the quick reply, here's the `.tf` file causing the issue:

```terraform
terraform {
  required_providers {
    vultr = {
      source = "vultr/vultr"
      version = "2.9.0"
    }
  }
}

resource "vultr_instance" "my_instance" {
  plan   = "vc2-1c-1gb"
  region = "sea"
  os_id  = "167"
}

```

**Comment by ddymko** [comment]
@da-edra 

Thanks for sharing - I can't replicate this using the `.tf` you provided.

Can you confirm that your API key has allowed access to IPv4 and Ipv6?
https://my.vultr.com/settings/#settingsapi

**Comment by denisse-dev** [comment]
I can confirm my API key is accessible from IPv4 and IPv4 addresses.

I also tried regenerating my API key and using a VPN in case my IP was rate limited or something but I'm still unable to deploy an instance using Terraform. My API key works with `vultr-cli` so it's definitely not an authentication or authorization issue.

Another thing is that I get the same error when trying to deploy any other resources (firewall, etc).

Are you also using Terraform v1.x.x?

![Screenshot from 2022-02-02 07-59-39](https://user-images.githubusercontent.com/10160626/152168057-0cd9bf33-103b-4712-b8ad-45499075f3f0.png)

**Comment by ddymko** [comment]
```
☁  tf  terraform version
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/vultr/vultr v2.9.0
```

hmmm...we'll have to poke around and see what the disconnect here is. Nothing stands out that would cause the ratelimiter to be hit.

**Comment by Oogy** [comment]
@da-edra Please run the apply again and provide us with the Terraform debug logs. This requires setting the following environment variables before running terraform:
```
export TF_LOG=TRACE
export TF_LOG_PATH=./tf-provider-vultr-issue-209.tflog
```
Then provide us with the contents of `tf-provider-vultr-issue-209.tflog`.

**Comment by denisse-dev** [comment]
Hi @Oogy , I pasted the log contents in a [gist](https://gist.github.com/da-edra/06f7c806c17e93e943f44fe2b7095f36)

Thank you!

**Comment by Oogy** [comment]
@da-edra We are working on a new builds of `govultr` and `terraform-provider-vultr` with better error handling so we can see whats going on here. We will provide an update soon.

**Comment by denisse-dev** [comment]
Thank you very much, Oogy.
I appreciate it. ☺️

**Comment by Oogy** [comment]
@da-edra The new builds have been released, please upgrade the Vultr Terraform Provider to `v2.9.1` and re-run the apply with debug logs.

**Comment by denisse-dev** [comment]
Thank you very much for the patch! Messages are more useful now.

This is the error I get: 

```
Error: error creating server: gave up after 4 attempts, last error : Post "https://api.vultr.com/v2/instances": dial tcp: lookup api.vultr.com on [::1]:53: read udp [::1]:33633->[::1]:53: read: connection refused
```

Here's a new revision of the logs: [tf-provider-vultr-issue-209-2.tflog](https://gist.github.com/denisse-dev/8abf58dd6488a69cae56eda98c25ca63)

I can confirm that I can use Vultr's API from the command line.
I deployed an identical instance without issues:

```bash
curl "https://api.vultr.com/v2/instances" \
  -X POST \
  -H "Authorization: Bearer ${VULTR_API_KEY}" \
  -H "Content-Type: application/json" \
  --data '{
    "region" : "mex",
    "plan" : "vhf-3c-8gb",
    "label" : "Example Instance",
    "os_id" : 535,
    "hostname": "my_hostname"
  }'
```

**Comment by Oogy** [comment]
@denisse-dev It appears your system is attempting to perform a DNS lookup to your local DNS server(perhaps systemd-resolved?) over IPv6. Please check your DNS configuration(`/etc/resolv.conf`), you may need to remove the IPv6 nameserver or make sure that your DNS server is listening on IPv6 at `::1`. 

Using the API from the CLI with curl is working because you are not specifying IPv6 to curl, it would likely fail with the same error if you did so.

**Comment by denisse-dev** [comment]
Thanks a lot for your help Oogy and ddymko, I really appreciate your commitment with improving your tools and providing great support! 

Closing this as it was indeed `systemd-resolvd`. :)
