### ISSUE TITLE
[BUG] - kubernetes cluster label is gone after updating its node pool

### ISSUE THREAD

**Issue by fhisamoto** [vultr/terraform-provider-vultr#234]
Given the k8s resource

```terraform
resource "vultr_kubernetes" "k8" {
  region  = var.region
  label   = "vke-staging"
  version = "v1.23.5+2"

  node_pools {
    node_quantity = 1
    plan          = "vc2-1c-2gb"
    label         = "np-3"
  }
}
```

When I update, for example, the node quantity to `2`, and run `terraform apply`, causes the k8s label to be gone. This can be seen in the web ui.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/32921/163427720-43e0613b-8b6b-4435-9de4-4207a55a9a41.png">
 
Or when using `data` like the example bellow

```terraform
data "vultr_kubernetes" "cluster" {
  filter {
    name   = "label"
    values = ["vke-staging"]
  }
}
```

raises the error

```
│ Error: no results were found
│ 
│   with module.k8s.data.vultr_kubernetes.cluster,
│   on ../../modules/k8s/main.tf line 28, in data "vultr_kubernetes" "cluster":
│   28: data "vultr_kubernetes" "cluster" {
```

**Comment by ddymko** [comment]
@fhisamoto Thanks for creating the ticket - We'll get this patched for the next release

**Comment by ddymko** [comment]
released in https://github.com/vultr/terraform-provider-vultr/releases/tag/v2.11.0
