### ISSUE TITLE
[BUG] - Cannot remove deprecated "tag" property from state

### ISSUE THREAD

**Issue by NicolasCARPi** [vultr/terraform-provider-vultr#252]
**Describe the bug**
My instance created 3 years ago from the web interface had the "Mail" tag. Now on terraform I imported it and use the new `tags` property, which is an array/list.

The problem is that the `tag` property is not removed/cleared, so every plan will have this:

![2022-05-12-151358_536x109_scrot](https://user-images.githubusercontent.com/3043706/168084475-c7878560-9f03-44be-ba5f-8c1deaea75f9.png)

The `tag` with value "Mail" stays visible in the state although the apply seems successful.

**To Reproduce**

1. Have an old instance with a unique tag.
2. Import this instance in your state
3. Use the `tags` property and omit the deprecated `tag` one to update the tags of the instance

**Expected behavior**
The old style `tag` is removed from state.

**Additional context**
Using terraform cloud, vultr provider 2.11.0

**Comment by ddymko** [comment]
@NicolasCARPi We'll look into this for you

**Comment by ddymko** [comment]
@NicolasCARPi 

This is an issue with the underlying go client. It doesn't allow emptying out the tag field.

As a workaround now you can remove the tag in your TF file along with removing the tag from my.vultr.com and then run `terraform refresh`

**Comment by NicolasCARPi** [comment]
@ddymko 

> you can remove the tag in your TF file

The `tag` is not present in the `.tf` file. I tried pulling the state, emptying manually the `tag` value from the json state file and pushing back the state to terraform cloud. But a subsequent run still wants to empty the `tag`.

> along with removing the tag from my.vultr.com

Problem is the tag is not visible in the web interface. Only the new style tags are present. So I cannot remove it from web interface.

> and then run terraform refresh

This command is deprecated and not available in cloud terraform (it is done during the plan anyway)
https://github.com/hashicorp/terraform/issues/23247#issuecomment-759608470

**Comment by ddymko** [comment]
@NicolasCARPi 

Thanks for the info! 

I went ahead and made https://github.com/vultr/govultr/issues/221 which once resolved we'll cut a new release of govultr and then update TF.

This will resolve the problem and allow for setting `""` on tag.

I was also thinking about a possible workaround for you. The APIv2 still has the ability to remove `tag` the field wasn't removed just deprecated. You can possibly send an API request to remove the `tag` and then do a reimport of the instance.

**Comment by NicolasCARPi** [comment]
> I went ahead and made https://github.com/vultr/govultr/issues/221 which once resolved we'll cut a new release of govultr and then update TF.

:+1: 

> I was also thinking about a possible workaround for you

Your workaround worked!

This is what I did (for anyone else encountering this issue):

~~~bash
# empty the tag value from api
curl "https://api.vultr.com/v2/instances/<instance_id>" -X PATCH -H "Authorization: Bearer ${VULTR_API_KEY}" -H "Content-Type: application/json" --data '{   "tag" : ""   }' 
# remove the instance from state
terraform state rm vultr_instance.my_instance
# import it back in state
terraform import vultr_instance.my_instance <instance_id>
~~~

And now it doesn't try to empty it at each run :tada: 

Side note, the documentation is using `tag` instead of `tags` in the curl example:
![2022-05-13-135652_285x217_scrot](https://user-images.githubusercontent.com/3043706/168285365-24c5af77-a589-4eb2-9b76-c91911ac17d7.png)


Thank you very much @ddymko for your help in this matter.

Best,
~Nico

**Comment by ddymko** [comment]
@NicolasCARPi glad to help

Ah, thanks for pointing out the API docs example! We'll patch that as well.
