### ISSUE TITLE
[BUG] - `vultr_kubernetes` data is unavailable when updating the node_pool.

### ISSUE THREAD

**Issue by fhisamoto** [vultr/terraform-provider-vultr#254]
Given I'm configuring the k8s cluster and helm provider as bellow:

```terraform
resource "vultr_kubernetes" "k8s" {
  region  = var.region
  label   = "my_label"
  version = "v1.23.5+2"

  node_pools {
    node_quantity = 2
    plan          = "vc2-1c-2gb"
    label         = "system"
  }
}

...

data "vultr_kubernetes" "cluster" {
  filter {
    name   = "label"
    values = [ "my_label" ]
  }
}
 
locals {
  kube_config = yamldecode(base64decode(data.vultr_kubernetes.cluster.kube_config))
}

provider "helm" {
  kubernetes {
    host                   = local.kube_config.clusters.0.cluster.server
    cluster_ca_certificate = base64decode(local.kube_config.clusters.0.cluster.certificate-authority-data)
    client_key             = base64decode(local.kube_config.users.0.user.client-key-data)
    client_certificate     = base64decode(local.kube_config.users.0.user.client-certificate-data)
  }
}

```

when using vultr provider `2.11.0` 
and changing, for example, the node quantity to `3`
Then I get the following error:

```
│ Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
│ 
│   with module.k8s_helm_packages.helm_release.redis,
│   on ../../modules/helm-packages/main.tf line 14, in resource "helm_release" "redis":
│   14: resource "helm_release" "redis" {
```

Looks like the data resource is unavailable when updating the `main` node pool.

Is this my code problem or a bug?

**Comment by ddymko** [comment]
> │ Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

This looks like a problem.

Can you confirm that your kubeconfig is working if you use it on its own?

**Comment by fhisamoto** [comment]
I'm able to get the cluster credentials using the code above when the `vultr_kubernetes` resource is untouched.

**Comment by ddymko** [comment]
@fhisamoto The kubeconfig is available on the resource https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/kubernetes#kube_config


Is there a reason you create a Kubernetes resource and then pull it down from a datasource?

**Comment by fhisamoto** [comment]
Let me test. I didn't notice that.

**Comment by fhisamoto** [comment]
works with the resource's `kube_config`. Thank you very much.
