### ISSUE TITLE
[BUG] - Typo in vultr_instance documentation

### ISSUE THREAD

**Issue by danielfdickinson** [vultr/terraform-provider-vultr#266]
**Describe the bug**
backups_schedule supports the following:
    [type](https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/instance#type) - Type of backup schedule Possible values are `daily`, `weekly`, `monthly`, `daily_alt_event`, or `daily_alt_odd`.

should read

backups_schedule supports the following:
    [type](https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/instance#type) - Type of backup schedule Possible values are `daily`, `weekly`, `monthly`, `daily_alt_even`, or `daily_alt_odd`.

That is `daily_alt_event` should `daily_alt_even`.

**Comment by optik-aper** [comment]
Thanks!  We'll get that fixed.
