### ISSUE TITLE
[BUG] - Incorrect resource type specificed in vultr_reverse_ipv6 example

### ISSUE THREAD

**Issue by uplime** [vultr/terraform-provider-vultr#267]
**Describe the bug**
The example usage in [vultr_reverse_ipv6](https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/reverse_ipv6) shows the following:

```
resource "vultr_reverse_ipv6" "my_reverse_ipv6" {
    instance_id = "${vultr_server.my_server.id}"
    ip = "${vultr_server.my_server.v6_networks[0].v6_main_ip}"
    reverse = "host.example.com"
}
```

However, there is no resource type named `vultr_server`. Based on the [vultr_reverse_ipv4](https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/reverse_ipv4) page, it looks like that should be a resource type of `vultr_instance` instead.

**To Reproduce**
1. Navigate to https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/reverse_ipv6
2. Attempt to run the example usage with `terraform plan`
3. Receive an error indicating that `vultr_server` is an undeclared resource

**Expected behavior**
Able to run the example usage without error.

**Screenshots**
NA

**Desktop (please complete the following information where applicable:**
 - OS: MacOS
 - Language Version: NA
 - Browser: Firefox
 - Version: 100.0

**Additional context**

NA

**Comment by optik-aper** [comment]
@uplime Thanks for reporting.  We'll get this fixed.

**Comment by uplime** [comment]
Thanks!
