### ISSUE TITLE
[Feature] - vke cluster upgrade without force replacement

### ISSUE THREAD

**Issue by fhisamoto** [vultr/terraform-provider-vultr#299]
Given I have created a cluster. When I chose to upgrade the vke version, the upgrade should not force replacement of my cluster. The cluster upgrade should be in-place, as is done by the web interface.

**Comment by optik-aper** [comment]
Thanks for the report.  We'll look into supporting this functionality soon.

**Comment by patademahesh** [comment]
+1

**Comment by optik-aper** [comment]
Added in #344
