### ISSUE TITLE
Custom import for `vultr_firewall_rule`.

### ISSUE THREAD

**Issue by rossigee** [vultr/terraform-provider-vultr#3]
While importing firewall rules, I get the following error:

```
$ terraform import module.vultr.vultr_firewall_rule.http 2f433dcd/6
Acquiring state lock. This may take a few moments...
module.vultr.vultr_firewall_rule.http: Importing from ID "2f433dcd/6"...
module.vultr.vultr_firewall_rule.http: Import prepared!
  Prepared vultr_firewall_rule for import
module.vultr.vultr_firewall_rule.http: Refreshing state... [id=2f433dcd/6]

Error: Error getting firewall rule : Invalid firewall group. Check FIREWALLGROUPID value and ensure your API key matches the account.
```

I'm quite sure the firewall group and rule id are correct, having checked them using `vultr-cli`. If I delete the firewall rule using the CLI or control panel, it then applies as expected.

**Comment by ddymko** [comment]
@rossigee 

I took a look into this. We don't official handle importing firewall rules - the issue you are running into is that when you try to get your firewall rules you need to pass in your firewall group id (rules live underneath groups). So when you are trying to get a firewall_rule its not getting the group id.

I ran dumped the TF logs and it is exactly that 
`2019-11-06T17:51:21.529-0500 [DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: GET /v1/firewall/rule_list?FIREWALLGROUPID=&direction=in&ip_type= HTTP/1.1`

We will have to look into getting a custom import that will handle this for you.

I am going to update this ticket so we can track this firewall_rule import as an enhancement
