### ISSUE TITLE
[BUG] - vultr_bare_metal_server tags inconsistent in sequential runs

### ISSUE THREAD

**Issue by johnjmartin** [vultr/terraform-provider-vultr#307]
**Describe the bug**
On no-op applies, vultr tags report as changed and attempt to update.

**To Reproduce**
example resource:
```
# main.tf
resource "vultr_bare_metal_server" "test-server" {
  label  = "johnlabeltest3"
  tags   = ["removable"]
  plan   = "vbm-8c-132gb-v2"
  region = "ewr"
  os_id  = 387
}
```

1. Create a new vultr_bare_metal resource:
```
$ terraform apply
# vultr_bare_metal_server.test-server["johnlabeltest3"] will be created
  + resource "vultr_bare_metal_server" "test-server" {
      + os_id            = 387
      + plan             = "vbm-8c-132gb-v2"
      + region           = "ewr"
      + tags             = [
          + "removable",
        ]
    }
```
2. apply the resource again after it's been created:
```
$ terraform apply
 # vultr_bare_metal_server.nomad_client_v2["johnlabeltest3"] will be updated in-place
  ~ resource "vultr_bare_metal_server" "nomad_client_v2" {
        id              = "xxxx"
      - tag             = "removable" -> null
        tags            = [
            "removable",
        ]
        # (17 unchanged attributes hidden)
    }
```

**Expected behavior**
sequential terraform applies with no changes to the resource should result in no updates to the resource.

**Screenshots**

**Desktop (please complete the following information where applicable:**
 - OS: Macos
```
Terraform v1.3.6
on darwin_arm64
+ provider registry.terraform.io/vultr/vultr v2.11.4
```

**Comment by optik-aper** [comment]
@johnjmartin thanks for the helpful info.  There was a change on the API which should have handled now in the 2.12.0 release.  Would you give it a try and report back?

**Comment by johnjmartin** [comment]
Thanks @optik-aper, looks like 2.12 did fix it!

**Comment by optik-aper** [comment]
@johnjmartin Glad to hear it!
