### ISSUE TITLE
[Feature] - vultr_kubernetes should support refreshing version changes

### ISSUE THREAD

**Issue by jtackaberry** [vultr/terraform-provider-vultr#311]
If one creates a VKE cluster via Terraform but subsequently uses the console to manage VKE cluster upgrades (which one might prefer to do as AFAICT there is no way to leverage VKE's upgrade orchestration via Terraform), this will cause tf state to diverge.

 `terraform refresh` should detect the cluster version change and update state accordingly.  Currently this can only be done through direct state manipulation.

**Comment by optik-aper** [comment]
#344 will allow updating the state via `terraform refresh`, but it's inadvisable to modify resources outside of terraform.  With the added upgrade functionality, you ought to be able to specify a new k8s version for the VKE cluster in the terraform config.  The caveat is that, if you upgrade the cluster outside of terraform now, it will throw an error:
![image](https://user-images.githubusercontent.com/8485770/230657077-f28ac7f8-dc16-4dc1-9d00-bca8a13eca69.png)
