### ISSUE TITLE
[Feature] - Managed database support

### ISSUE THREAD

**Issue by nickygerritsen** [vultr/terraform-provider-vultr#315]
**Is your feature request related to a problem? Please describe.**
Currently creating managed databases (MySQL, PostgreSQL, Redis) is not possible with this provider.

**Describe the solution you'd like**
Add support for managing managed databases.

**Additional context**
Looking at the (public) Vultr API documentation it seems databases are not supported there yet either, so probably this first requires an update to the API.

**Comment by optik-aper** [comment]
@nickygerritsen Thanks for the issue.  It's on the roadmap but you're right, it has to start in the API and then we can add it to the various providers.

**Comment by NicolasCARPi** [comment]
Hello,

What's the status of this feature request? It seems to me it's a pretty critical feature if one wants to manage all resources through Terraform.

**Comment by optik-aper** [comment]
@NicolasCARPi It's nearing completion.  We will probably have it wrapped up and released this week.

**Comment by NicolasCARPi** [comment]
@optik-aper Oh that's great to know! :tada:

**Comment by optik-aper** [comment]
Support added in PR #352

**Comment by NicolasCARPi** [comment]
@optik-aper Do you know why it doesn't show up in https://registry.terraform.io/providers/vultr/vultr/latest/docs ? It is showing the 2.15.0 version so it is aware of the new version, but I do not see the `vultr_database` in the resources.

**Comment by optik-aper** [comment]
Oh, it looks like those got missed.  We'll circle back and update them.  Sorry about that!
