### ISSUE TITLE
[BUG] - missing firewall rule does not trigger create, instead 404s

### ISSUE THREAD

**Issue by unusualevent** [vultr/terraform-provider-vultr#321]
**Describe the bug**
Deleted resource on the UI causes vultr's terraform provider to error out.

**To Reproduce**
1. create a firewall with some rules in terraform
2. delete one of the rules in the Vultr GUI
3. try running terraform plan or apply

**Expected behavior**
Vultr's terraform module should gracefully note that the firewall rule doesn't exist anymore, and plan on creating it.

**Observed Behavior**
 Error: error getting firewall rule some_id: {"error":"Firewall rule ID not found.","status":404}

**workaround, in case Vultr doesn't fix their provider**

terraform state rm vultr_firewall_rule.rule_name

**Comment by optik-aper** [comment]
Thanks for the report.  I'll get this patched.
