### ISSUE TITLE
[BUG] - error creating kubernetes cluster, status 400

### ISSUE THREAD

**Issue by maxkokocom** [vultr/terraform-provider-vultr#332]
**Describe the bug**
I am trying to create k8s cluster and I am getting an error code which does not provide information what's the error cause.

```
vultr_kubernetes.k8: Creating...
╷
│ Error: error creating kubernetes cluster: {"error":"Bad request.","status":400}
│ 
│   with vultr_kubernetes.k8,
│   on main.tf line 1, in resource "vultr_kubernetes" "k8":
│    1: resource "vultr_kubernetes" "k8" {
│ 
```

**To Reproduce**
```hcl
resource "vultr_kubernetes" "k8" {
    region = "lhr"
    label     = var.cluster_name
    version = "v1.26.2+1"
}

# This resource must be created and attached to the cluster
# before removing the default node from the vultr_kubernetes resource
resource "vultr_kubernetes_node_pools" "np" {
    cluster_id = vultr_kubernetes.k8.id
    node_quantity = 1
    plan = "vhp-2c-2gb-amd"
    label = var.cluster_name
    auto_scaler = true
    min_nodes = 1
    max_nodes = 3
}
```

**Expected behavior**
 I expected a k8s cluster created or verbose error explaining why API call failed.

**Comment by optik-aper** [comment]
@maxkokocom The kubernetes resource is a little odd in how it's defined in the terraform configs.  Per the API requirements, a new cluster has to have an associated node pool.  The way you've defined it, terraform will try to create a cluster without a node pool and then try to create a node pool and associate it with the cluster.  The correct way to do this is:
```terraform
resource "vultr_kubernetes" "k8" {
    region = "lhr"
    label     = "issue-332"
    version = "v1.26.2+2"

  node_pools {
       node_quantity = 1
       plan = "vhp-2c-2gb-amd"
       label = "issue-332-nodepool"
       auto_scaler = true
       min_nodes = 1
       max_nodes = 3
  }
}
```
And if you wish to attach more node pools at a later time, you can create a separate node pool resource similar to what you initially defined:
```terraform
resource "vultr_kubernetes_node_pools" "np" {
    cluster_id = vultr_kubernetes.k8.id
    node_quantity = 1
    plan = "vhp-2c-2gb-amd"
    label = var.cluster_name
}
```
Hopefully that will help you but if not, feel free to re-open.
