### ISSUE TITLE
[Feature] - Ability to scale additional node pools to zero replicas

### ISSUE THREAD

**Issue by baznikin** [vultr/terraform-provider-vultr#360]
**Is your feature request related to a problem? Please describe.**
Not sure where to open this feature request, redirect me to better place.
I'd like to scale down node pool to zero nodes. Use case - we run very heavy CI/CD jobs to test and build application. We need pricey nodes for it. However, our developers do not work 24/7, active development occurs 8-10 hours 5 days per week. I want to run k8s cluster with cheap default node pool and additional node pool of high performance servers with autoscaling.

Terraform plovider allows to create pool with such definition:
```
resource "vultr_kubernetes_node_pools" "gitlab-runner" {
    cluster_id = vultr_kubernetes.k8.id
    node_quantity = 1
    plan = "vc2-6c-16gb"
    label = "gitlab"
    tag = "gitlab"
    auto_scaler = true
    min_nodes = 0
    max_nodes = 5
}
```
but it never scale to 0 nodes:
```
I0512 11:42:28.747447       1 static_autoscaler.go:511] No unschedulable pods
I0512 11:42:28.747880       1 pre_filtering_processor.go:67] Skipping gitlab-43e1054830ff - node group min size reached (current: 1, min: 1)
I0512 11:42:28.748087       1 legacy.go:298] No candidates for scale down
```

**Describe the solution you'd like**
Allow to scale node pool to zero if other nodes remains in cluster.

**Comment by optik-aper** [comment]
This isn't supported by the Vultr platform, unfortunately.  If that changes we'll support it here.
