### ISSUE TITLE
 Error: error getting SSH keys: {"error":"Invalid ssh key.","status":404}

### ISSUE THREAD

**Issue by Sophrinix** [vultr/terraform-provider-vultr#371]
**Describe the bug**
This morning at 8:30am pst I was in the middle of a deploy and got the following error:
vultr_ssh_key.ssh_public_key: Refreshing state... [id=395bbf58-c1ae-458b-8fe8-REDACTED]
╷
│ Error: error getting SSH keys: {"error":"Invalid ssh key.","status":404}
│ 
│   with vultr_ssh_key.ssh_public_key,
│   on main.tf line 22, in resource "vultr_ssh_key" "ssh_public_key":
│   22: resource "vultr_ssh_key" "ssh_public_key" {
│ 
╵
Installation completed

about 20 minutes later, I tried to do an terraform destroy and got:
ultr_ssh_key.ssh_public_key: Refreshing state... [id=395bbf58-c1ae-458b-8fe8-REDACTED]
╷
│ Error: error getting SSH keys: {"error":"Invalid ssh key.","status":404}
│ 
│   with vultr_ssh_key.ssh_public_key,
│   on main.tf line 22, in resource "vultr_ssh_key" "ssh_public_key":
│   22: resource "vultr_ssh_key" "ssh_public_key" {
│ 
╵
Installation completed

There was no change of any code or keys on my side.

**To Reproduce**
Try to use this provider. it fails currently.

**Expected behavior**
I expect it to successfully execute the process of standing up vultr servers and configuring them as per my playbooks
client OS:
MacOS 13.4.1 (22F82)

I do not expect the client OS to be relevant, but including just in case.

One question I do have is what version of the Vultr API is this provider using? Presumably it is API version 2.

**Comment by optik-aper** [comment]
@Sophrinix thanks for the report.  Would you be able to give an example `.tf` config that you are using when this occurs?

**Comment by Sophrinix** [comment]
https://github.com/sceptic30/ansible-terraform-kubernetes-vultr

this is a good test bed.

**Comment by optik-aper** [comment]
Do you have anything more specific?  I don't have any issues with SSH keys during create/destroy with a simple instance like 
```terraform
resource "vultr_ssh_key" "ssh_key" {
  name    = "tf-ssh-key"
  ssh_key = "..."
}

resource "vultr_instance" "k8s-master" {
  plan                   = "vc2-2c-4gb"
  region                 = "ams"
  os_id                  = 1946
  label                  = "tf-k8s-master server"
  hostname               = "tf-k8s-master"
  enable_ipv6            = true
  backups                = "disabled"
  activation_email       = false
  ddos_protection        = false
  ssh_key_ids            = ["${vultr_ssh_key.ssh_key.id}"]
}
```

**Comment by Sophrinix** [comment]
The solution to this problem turned out to be that one should always check their versions on the provider(s) they are using.
While it was strange it randomly failed while in the middle of a deploy yesterday once I moved from version 2.3.0  to 2.15, this provider began to work again. 

There was no obvious indication that this would resolve the issue, but since the error was non-sense, it was worth trying.

**Comment by optik-aper** [comment]
Glad to hear it's working again. Thanks for the update!
