### ISSUE TITLE
[BUG] - Output variable `internal_ip` displays the empty string.

### ISSUE THREAD

**Issue by rperper** [vultr/terraform-provider-vultr#373]
**Describe the bug**
Output variable `internal_ip` displays the empty string after a successful apply.

**To Reproduce**
In my environment I created the following Bob1.tf file:
```
resource "vultr_instance" "Bob1" {
  count = var.Bob1_count
  snapshot_id = "d4edbd21-8c7a-4129-b001-a3bbc9bfae8f"
  plan = "vc2-1c-1gb"
  region = "ewr"
  tags = [ var.Bob1_label ]
}

variable "Bob1_count" {
  type = number
  default = 0
}

variable "Bob1_label" {
  type = string
  default = ""
}

output "Bob1_ipaddr" {
  value = resource.vultr_instance.Bob1[*].internal_ip
}
```
Then did the following:
```
terraform apply -var=Bob1_count=1
```
Upon success the output displays the empty string for the `Bob1_ipaddr` variable.  If I use `main_ip` instead it works correctly.

**Expected behavior**
Output the internal VPC IP address for the node.

**Screenshots**
N/A

**Desktop (please complete the following information where applicable:**
 - OS: Ubuntu 22.04
 - Language Version [e.g. PHP7, Go 1.12]: Terraform v1.5.0.  Vultr terraform provider 2.15.1.
 - Browser [e.g. stock browser, safari]: N/A
 - Version [e.g. 22]: N/A

**Additional context**

**Comment by optik-aper** [comment]
This is a behavior of the API so I'm going to close it out here since it's not directly related to the terraform provider.  But, in researching this, it looks like `internal_ip` is only populated when a VPC is attached.  For the IP of the instance, you'd want to reference `main_ip`.  We'll update the docs to help clarify that.

**Comment by rperper** [comment]
Yes, this was a bug on my part.  Once I included `vpc_ids` all was well.  Thanks for closing it.
