### ISSUE TITLE
[Feature] - Binary releases of the terraform-provider-vultr for openbsd_amd64 platform

### ISSUE THREAD

**Issue by shawnmchugh** [vultr/terraform-provider-vultr#379]
Is your feature request related to a problem? Please describe.
There are no vultr terraform provider binary releases built for openbsd_amd64.

Describe the solution you'd like
I'd like to see binary releases for OpenBSD as well please.

Describe alternatives you've considered
I do build the provider from source, but it gets annoying.

Additional context
Vultr has first class support for OpenBSD as a virtual machine option, so it's odd that there isn't a Terraform provider built for the platform.

**Comment by optik-aper** [comment]
We should be able to add these for the next release.

**Comment by optik-aper** [comment]
You can find the OpenBSD amd64 release under the assets [here](https://github.com/vultr/terraform-provider-vultr/releases/tag/v2.16.1)
