### ISSUE TITLE
Attach instance to loadbalancer

### ISSUE THREAD

**Issue by nishit93-hub** [vultr/terraform-provider-vultr#381]
Hi All,

I want to know how we can attach instances to load balancers using `terraform`. Can anyone provide an example?

**Comment by optik-aper** [comment]
You can find docs on the load balancer resource over [here](https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/load_balancer).  Here's a simple example of how you would create an instance, VPC and load balancer, all connected in terraform:
```terraform
resource "vultr_instance" "oof" {
  region = "mel"
  tags = ["terraform"]
  label = "tf-lb-test"
  plan = "vhp-2c-2gb-amd"
  os_id = 1743
}

resource "vultr_vpc" "bar" {
  region   = "mel"
  description = "bar"
}

resource "vultr_load_balancer" "foo" {
  region   = "mel"

  forwarding_rules {
    frontend_protocol = "http"
    frontend_port     = 80
    backend_protocol  = "http"
    backend_port      = 80
  }
  vpc = vultr_vpc.bar.id
  attached_instances = [vultr_instance.oof.id]
}
```
Hope that helps!

**Comment by nishit93-hub** [comment]
Hi,

Thanks for the example. That worked!!

**Comment by optik-aper** [comment]
Excellent!
