### ISSUE TITLE
[Feature] - Add support for vpc 2.0 resource

### ISSUE THREAD

**Issue by meldafrawi** [vultr/terraform-provider-vultr#386]
**Is your feature request related to a problem? Please describe.**
Vultr has introduced VPC 2.0, User should be able to create a VPC 2.0 resource and attach other resources to it. 

**Describe the solution you'd like**
create vpc 2.0 resource and data resource

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ogawa0071** [comment]
I have completed the implementation and submitted a pull request.
https://github.com/vultr/terraform-provider-vultr/pull/389

**Comment by optik-aper** [comment]
VPC2 was released in v2.16.0
