### ISSUE TITLE
When creating domains, remove default records

### ISSUE THREAD

**Issue by SamWhited** [vultr/terraform-provider-vultr#42]
When creating a domain Vultr adds several default records (a wildcard CNAME, an MX record that probably doesn't point to your mailserver, etc.) that I would hazard a guess are unwanted 99% of the time. This means that the process for creating a new domain with Terraform either involves logging into your control panel to remove the records, or creating resources for them, importing those records (which I think is unsupported, but in theory you could do this), and then removing them. This is cumbersome.

Instead, if we're using Terraform we should remove all records from the domain after creating it so that the user can start from a fresh slate and create records in their Terraform config themselves.

**Comment by ddymko** [comment]
We are current in the process of creating V2 of the Vultr API which will address a lot of pain points of current API behavior. One of which being the ability to create empty domains.

**Comment by ddymko** [comment]
closing in favor of 47

**Comment by SamWhited** [comment]
Ah okay, I wasn't sure if these were actually the same problem. Thanks
