### ISSUE TITLE
[BUG] - Issue with the Terraform s3 backend and documentation

### ISSUE THREAD

**Issue by echoboomer** [vultr/terraform-provider-vultr#426]
**Describe the bug**
In the latest `terraform` release, `1.6.3` at time of testing, the `endpoint` parameter does not work anymore and it fails to `init` since it has been deprecated. It should be `endpoints.s3` now.

Furthermore, a new parameter, `skip_requesting_account_id`, is required when configuring the `s3` backend for use with Vultr. Otherwise, initialization fails.

This example works properly:

```hcl
terraform {
  backend "s3" {
    bucket = "my-bucket"
    key    = "terraform.tfstate"
    endpoints = {
      s3 = "https://ewr1.vultrobjects.com"
    }
    region = "us-east-1"

    skip_requesting_account_id  = true
    skip_credentials_validation = true
  }
}
```

I think the [docs](https://www.vultr.com/docs/how-to-store-terraform-state-in-vultr-object-storage/) simply need to be updated for use with whatever `terraform` version introduced this change. Forgive me if this has already been mentioned - feel free to close.

**To Reproduce**
1. Try using the provider for Vultr with existing settings outlined here.

**Expected behavior**
`terraform init` should pass.

**Screenshots**
![image](https://github.com/vultr/terraform-provider-vultr/assets/19732751/43615a5b-5025-41c1-9596-1ca29c951c06)

**Desktop (please complete the following information where applicable:**
 - Language Version [e.g. PHP7, Go 1.12]

**Additional context**

**Comment by optik-aper** [comment]
Hello @echoboomer.  That appears to be with the s3 backend which has [documented](https://developer.hashicorp.com/terraform/language/settings/backends/s3#s3-state-storage):

[endpoint](https://developer.hashicorp.com/terraform/language/settings/backends/s3#endpoint) - (Optional, Deprecated) Custom endpoint URL for the AWS S3 API. Use endpoints.s3 instead.

That doesn't appear to be related to the Vultr terraform provider so I'm going to close this.

**Comment by echoboomer** [comment]
@optik-aper thanks for following up. This was my bad for opening this without thinking since it surprised me when using a newer version of the AWS provider.

The one thing I'll ask is that the documentation on the page I linked should be updated to either notify users about this change in the backend configuration or update it.

**Comment by optik-aper** [comment]
@echoboomer I'll pass along the feedback.  Thanks!

**Comment by Jarmos-san** [comment]
Hi @echoboomer!

Thanks for the fix you provided. Our pipeline broke and when we were looking around for a solution, the first result on the Google SERP was the exact blog post you shared. It is definitely outdated and should be updated as early as possible considering how high up it shows up on the search results!

Had we stumbled upon your suggestion earlier, we would not have wasted a couple of hours pulling off our hair! 😅
