### ISSUE TITLE
Creating A record makes domain unmanaged by Terraform

### ISSUE THREAD

**Issue by SamWhited** [vultr/terraform-provider-vultr#47]
To reproduce create a new domain in the Terraform config and apply. Now login and remove all the default records in the UI. Then create an A record in the Terraform config and apply.

The domain is no longer recognized as the same one, and terraform can't recreate it because it already exists. You have to go through and manually use `terraform state rm` to remove every domain individually (because it doesn't support wildcards) from the config and reapply. If you redeploy your server, the same thing will happen again even if you don't create an A record and just rely on the domain's `server_ip` field because the IP will change and the domain won't be recognized.

I know this is probably also an API issue and will be fixed in the v2 API, but as far as I can tell using Terraform to manage your DNS is completely unusable at the moment because you can't re-import the domain, can't ever redeploy your server because that might change your IP, etc. Unfortunately, managing DNS manually isn't an option because every time our site deploys we don't want it to be broken and down, lets encrypt provisioning failing, etc. until we can go in and change the A/AAAA records by hand.

I know it doesn't feel good working on things when you have a new and shiner thing coming out to replace them, but please at least provide some sort of workaround for this. I'm completely stuck and have invested a lot of time into trying to get setup on Vultr. All the various DNS/Terraform issues are costing us a lot of time, but I think moving everything over to another provider would take even longer so I'm really not sure what to do.

Thanks for your time and consideration.

**Comment by ddymko** [comment]
related to #42

**Comment by ddymko** [comment]
@SamWhited 

I'll work on a patch to get this behavior squared away. I'll make the `server_ip` an optional field which if omitted will create the domain and then clear out all of the records. I'll also remove the current dependency on `server_ip` on the domain read. 

These changes should then offer the same experience we will have in v2 (and other providers)

**Comment by SamWhited** [comment]
Thank you so much for your time; if there's any way I can help, please let me know!

**Comment by ddymko** [comment]
@SamWhited 

I just pushed up a PR that will allow you to create empty zones. If you want would want to pull down the PR and test (in addition to the code review + testing that we will do) that would be greatly appreciated
