### ISSUE TITLE
`vultr_ssh_key` resources modified on every run

### ISSUE THREAD

**Issue by rossigee** [vultr/terraform-provider-vultr#5]
When I run a configuration that includes `vultr_ssh_key` resource definitions, it considers the SSH keys as having changed each time it's run, even after it's applied the (non)change from a previous run.

To elaborate, the resource definition looks like this...

```
resource "vultr_ssh_key" "rossg" {
  name = "rossg"
  ssh_key = file("${path.module}/sshkeys/rossg.pub")
}
```

When applied...

```
$ terraform apply -target=module.vultr.vultr_ssh_key.rossg
Acquiring state lock. This may take a few moments...
module.vultr.vultr_ssh_key.rossg: Refreshing state... [id=5da7cd9a83bf7]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.vultr.vultr_ssh_key.rossg will be updated in-place
  ~ resource "vultr_ssh_key" "rossg" {
        date_created = "2019-10-16 22:10:34"
        id           = "5da7cd9a83bf7"
        name         = "rossg"
      ~ ssh_key      = <<~EOT
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvEEM09rqCFaiv0u0vg8c2FHRPZpOlQ1DzXWLcgnH/2APUElHk6KtYPQZeaIMQRHBUsABrqwBimBlJAss4k8Wf3y/eqsCyNBezZoSoslJPuKpVxzLs3j4pdvKO3FuJy7792CgMLyvVrJ9bA/PYfb4BAkzAeXrwyZFvoib1+SHAz6QH/VWtIpzZYR9GbETg5nd8AXYAVVMnLW+jn5PMyZBrAU70gy/ga3jAj8lvNj+Kq3HdEu/0QA5M3cfnJpRWBLpEghX1GbkjR+sA6gYBgvt3HMyjI+fFNAJg2JtMV1rXzWQQWDIbRjkQIfnC/yJ/CousoZ+c/VpirhiFImh0emF5 rossg
        EOT
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.vultr.vultr_ssh_key.rossg: Modifying... [id=5da7cd9a83bf7]
module.vultr.vultr_ssh_key.rossg: Modifications complete after 2s [id=5da7cd9a83bf7]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
Releasing state lock. This may take a few moments...
```
(excessive warning text about use of '-target' removed from above output)

Actual behaviour: Despite the 'modifications complete' message, If I now run the command again, it wants to apply the exact same update - ad infinitum.

Expected behaviour: It should recognise that the key has not been changed, and should not propose to update it.

**Comment by ddymko** [comment]
@rossigee 

There is nothing that our provider (or our API) would do that would cause this kind of drift. The reason you are getting this kind of drift looks like it may be from the `<<~EOT` which is done through terraform-core. This is done through the diff process.

I also tried to see if I could replicate your issue and created this resource block

```hcl
resource "vultr_ssh_key" "dym" {
  name = "dym"
#   ssh_key = file("${path.module}/sshkeys/dym.pub")
#   ssh_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8fmKDq9mi4CSHyx691/gDqGWXLhvMSZ9YBv1xBBrAEojbgROvaSGpeA1NE+7kbbY5aCZMhdxAQsSxVjBTIOtMsJA96ns6i"
}
```

I would uncomment/comment one or the other and see if I would see a difference if i ran a `terraform apply` or `terraform apply -target=module.vultr.vultr_ssh_key.dym` and it did not notice any differences between the two. I have a feeling this may be something with the file function.

I'll spend some more time looking into this but it seem

**Comment by ddymko** [comment]
Spent some more time digging into this. It looks like this is more of a terraform core type scenario since we do not handle any of the logic during `apply` `plan`.
