### ISSUE TITLE
[BUG] - `user_scheme` field is forcing re-creation when not set in config

### ISSUE THREAD

**Issue by optik-aper** [vultr/terraform-provider-vultr#524]
**Describe the bug**
When updating to v2.22.0 which adds the `user_scheme` field, terraform thinks that it needs to re-create any instance without a value matching what is grabbed in the `Read`

**Comment by solson** [comment]
In case it helps anyone else who ends up googling this, I was having an issue with this change in Pulumi for my pre-existing vultr_instance, but all I needed to do was run `pulumi refresh` to read `user_scheme: "root"` from the Vultr API into the state before running `pulumi up`, to make it see an empty diff.
