### ISSUE TITLE
Object storage resource documentation

### ISSUE THREAD

**Issue by davidsbond** [vultr/terraform-provider-vultr#54]
I wanted to terraform my vultr object storage but couldn't tell if it was supported or not without looking at the plugin code.

It looks like https://www.terraform.io/docs/providers/vultr/index.html doesn't have any documentation yet for the object storage resources.

**Comment by ddymko** [comment]
Hey @davidsbond object storage is supported.

Looks like the sidebar is missing the object storage links but you can access them here for now
https://www.terraform.io/docs/providers/vultr/d/object_storage.html
https://www.terraform.io/docs/providers/vultr/r/object_storage.html

Thanks for pointing this out we'll get this squared away!

**Comment by davidsbond** [comment]
Thanks! Am enjoying using Vultr!
