### ISSUE TITLE
[BUG] - ddos_protection does nothing when set

### ISSUE THREAD

**Issue by davidsbond** [vultr/terraform-provider-vultr#58]
**Describe the bug**
I want to enable DDOS protection on a production server via terraform. When I set the `ddos_protection` flag on the `vultr_server` and run `terraform apply` it does not appear to enable DDOS protection

**To Reproduce**
1. Create a `vultr_server` resource via terraform without `ddos_protection` set
2. Update the `vultr_server` resource so `ddos_protection = true`
3. Run `terraform apply`
4. DDOS protection is not enabled in the web UI

**Expected behavior**
When `ddos_protection` is set to `true`, it should enable DDOS protection on the server

**Additional context**

I'm using v1.3.2 of the provider plugin

**Comment by ddymko** [comment]
@davidsbond There currently is no call in v1 to update an instance with DDOS once it has been created.

We will have to add in API functionality to allow enabling/disabling of DDOS protection for existing instances in v1.

Once these new API calls have been published I will update govultr and then update terraform to support this.
