### ISSUE TITLE
Custom import for  `vultr_dns_record`

### ISSUE THREAD

**Issue by zoltanpetrik** [vultr/terraform-provider-vultr#6]
I've tried doing `terraform import` according to the documentation, and failed.

_I've replaced sensitive information with placeholder data._

If I execute the following command:

`vultr-cli dns record list domain.com`

I get the following correct result

```
ID              TYPE    NAME    DATA            PRIORITY        TTL
12345678        A               123.123.123.123 -1              300
** MULTIPLE LINES OMITTED **
```

So I have the ID necessary to run the `terraform import` command for the `vultr_dns_record` resource.

My `main.tf` looks like:

```
provider "vultr" {
  api_key = "************************************"
  rate_limit = 700
}

resource "vultr_dns_domain" "foo" {
  domain = "domain.com"
  server_ip = "123.123.123.123"
}

resource "vultr_dns_record" "bar" {}
```

I've tried adding `domain = "domain.com"` into the `"bar"` resource, but it makes no difference.

Then if I run the following command:

`terraform import vultr_dns_domain.foo domain.com`

It runs correctly.

Then if I run the following command with `export TF_LOG=trace`:

`terraform import vultr_dns_record.bar 12345678`

OR

`terraform import vultr_dns_record.bar domain.com`

I get the following result either way:

```
[INFO] Terraform version: 0.12.13
[INFO] Go runtime version: go1.12.9
[INFO] CLI args: []string{"/usr/local/bin/terraform", "import", "vultr_dns_record.bar", "12345678"}

** MULTIPLE LINES OMITTED **

[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: 2019/11/13 13:14:32 [DEBUG] Vultr API Request Details:
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: ---[ REQUEST ]---------------------------------------
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: GET /v1/dns/records?domain= HTTP/1.1
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: Host: api.vultr.com
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: User-Agent: Terraform/0.12.0
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: Accept: application/json
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: Api-Key: ************************************
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: Accept-Encoding: gzip
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4:
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4:
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: -----------------------------------------------------
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: 2019/11/13 13:14:33 [DEBUG] Vultr API Response Details:
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: ---[ RESPONSE ]--------------------------------------
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: HTTP/1.1 412 Request Failed
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: Transfer-Encoding: chunked
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: Connection: keep-alive
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: Content-Type: text/html; charset=UTF-8
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: Date: Wed, 13 Nov 2019 12:15:14 GMT
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: Server: nginx
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: X-User: **********************
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4:
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: 59
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: Invalid domain.  Check domain value and ensure your API key matches the domains's account
[DEBUG] plugin.terraform-provider-vultr_v1.0.5_x4: 0

** MULTIPLE LINES OMITTED **
```

And the `terraform.tfstate` does not update as it should.

Please note that the `GET /v1/dns/records?domain=` request does not contain the domain as it should.

I've tried looking into the source, but I'm not fluent in go, so I'm not sure what is going on.

It works with importing `vultr_dns_domain` resources, so is this a bug, or am I doing something wrong?

**Comment by ddymko** [comment]
Hey @Zoltanpetrik 

This issue is similar to #3 

We don't official handle importing dns records. As you pointed out the domain name is not being passed to the request which is why the import does not work. This needs a custom importer which will take in the domain name and pass it off to the request.

I will convert this ticket so it can be used to track a custom import for `vultr_dns_record`
