### ISSUE TITLE
[Feature] - Implement vultr_regions datasource that returns all datacenters

### ISSUE THREAD

**Issue by sc0rp10** [vultr/terraform-provider-vultr#63]
It'd be nice if we can use vultr_regions that returns all available regions to use.
For example we need to deploy an instance at each available datacenter (including newly created by Vultr in advance).
Right now I using http-datasource in combination with `https://api.vultr.com/v1/regions/list` but i'm not sure about this way.
I think it might be looks like:
```
data "vultr_regions" "regions" {
  filter {
    name   = "name"
    values = ["*"]
  }
}

locals {
    nodes = flatten([ /* iterate over regions and create a vultr_server record */])
}

resource "vultr_server" "vultr-vm" {
    for_each = local.nodes
}
```
What do you think about it?

**Comment by ddymko** [comment]
Hey @sc0rp10 this isn't something we will plan on adding since like you pointed out you can use the `http-datasource` to build out the with all of the regions for you to loop through
