### ISSUE TITLE
[BUG] - breaking changes in vultr_server.server.user_data encoding handling without documentation

### ISSUE THREAD

**Issue by NickCao** [vultr/terraform-provider-vultr#64]
**Describe the bug**
The attribute vultr_server.server.user_data used to accept raw user data string without base64 encoding, while upstream changes in the govultr library changed it's behavior to accept encoded data, and the change is not reflected in documents.

**To Reproduce**
1. define a vultr_server.server resource
2. set it's user_data attribute to non base64 encoded value
3. terraform apply
4. got error: error occured while updating user_data for server ID : Invalid user-data (check base64 encoding)

**Expected behavior**
Either add additional encoding to mimic the previous behavior, or update the documents to reflect the new one.
Personally prefer the first solution, as it makes the diff output of terraform plan more human readable and won't break existing resources.

**Comment by ddymko** [comment]
@NickCao 

This was on oversight on our part. Thanks for pointing this out we will get it patched and we will keep behavior the same way it was.
