### ISSUE TITLE
[Feature] - Replace instance when `user_data` changes

### ISSUE THREAD

**Issue by nsmith5** [vultr/terraform-provider-vultr#69]
**Is your feature request related to a problem? Please describe.**
In using Fedora CoreOS with vultr terraform, when I update the `user_data` with a new ignition file I don't get an updated server. Fedora CoreOS, like other user_data provisioned systems that attempt to create immutable infrastructure, only reads `user_data` on first boot. This means that you need to replace the old server with a new one to realize the change made to the `user_data`.

**Describe the solution you'd like**
Replace a `vultr_server` when the `user_data` changes.

**Describe alternatives you've considered**
😬 Can't think of a scalable one. You'd hope terraform might supply something that would help in the `lifecycle` block, but no. I've been running `terraform destroy` and `terrafrom apply` in a loop as I develop, but that doesn't scale to a larger system than one server.

**Additional context**
FWIW, this change would match `aws_instance` behaviour.

**Comment by NickCao** [comment]
This feature can actually be accomplished with a null resource.
And I've got an example here: [null resource](https://nichi.co/posts/2020-09-13-terraform-with-fedora-coreos/)

**Comment by nsmith5** [comment]
Oh nice, thanks for the work around! Sounds like @ddymko is willing to change the behaviour to do this automatically, so that is exciting :D
