### ISSUE TITLE
[BUG] - Unable to get firewall_group

### ISSUE THREAD

**Issue by cooperaj** [vultr/terraform-provider-vultr#81]
**Describe the bug**
When running my terraform using the new v2 plugin I'm getting errors around the firewall group component (having fixed all the migration issues... you should probably document those)

**To Reproduce**
Have a firewall group config that looks like (maybe created with a prior version?)
```
resource "vultr_firewall_group" "vpn_firewall" {
  description = "Firewall for VPN servers"
}
```

Run `terraform apply`

See
```
Error: error getting firewall group ID_GOES_HERE : {"error":"invalid resource format","status":400}
```

**Expected behavior**
The apply succeeds. 

**Desktop (please complete the following information where applicable:**
 - OS: MacOS Big Sur
 - Language Version: Terrafrom 0.13
 - Version: v2

**Comment by ddymko** [comment]
@cooperaj 

Is the ID for the firewall group in a UUID format or is this from an existing v1 TF build?

**Comment by cooperaj** [comment]
It looks like this is an id issue. I've gone through and manually removed and reimported the groups and all the rules (as it appears the id's have changed there too) and its now working.

My issue now is that it's trying to replace all my instances because of the 'activation_email'. Which is madness as I don't care but I can't seem to have it ignore that :/

I've done the same thing and removed/reimported but it's refusing to register the flag. Sorry, I realise this isn't a support forum.

**Comment by ddymko** [comment]
Unfortunately, our V1 API was in dire need an update as it was very inconsistent, very small rate limit, among other things. Hence the big undertaking to release all new V2 tooling that utilizes the new API. So we know there is a bit of a pain having to do a large transition from v1 to v2.

If there are bugs/issues please let us know and we'll dig into them.

**Comment by cooperaj** [comment]
I've added what I consider to be a bug in that the import code does not create a valid state for an instance (one that will then apply without proposing changes). This can be closed though I think that the changes to ID's should probably be documented somewhere

**Comment by ddymko** [comment]
Thanks! We'll look into the other ticket and we'll make some updates to the readme and some other places denoting that API v2 uses UUIDs now

**Comment by cooperaj** [comment]
> Thanks! We'll look into the other ticket and we'll make some updates to the readme and some other places denoting that API v2 uses UUIDs now

firewall rules appear to use sequential numbers (1, 2, 3 etc)
