### ISSUE TITLE
[BUG] - Import of vultr instance does not produce valid state entry

### ISSUE THREAD

**Issue by cooperaj** [vultr/terraform-provider-vultr#82]
**Describe the bug**
I've upgraded to v2 of the provider and have been working to fix the migration issues. This last one has me a bit stumped and I've had to resort to manually editing the state file (big no no)

**To Reproduce**
1. Migrate 'vultr_server' to 'vultr_instance' in tf files.
2. Remove server from state (terraform state rm vultr_server.SERVER)
3. Import (terraform import vultr_instance.SERVER SERVER_ID_FROM_API)
4. `terraform apply`
5. See failures that require a destroy/rebuild of the server. (activation_email?)

**Expected behavior**
Apply should result in no proposed state changes

**Desktop (please complete the following information where applicable:**
 - OS: MacOs Big Sure
 - Language Version: Terraform 0.13
 - Version: v2

**Comment by cooperaj** [comment]
It's worth noting that ssh_keys also cause a ForceNew - which I guess is right but again, the import fails to bring that info into the state so an apply will destroy a working server with that ssh_key already applied

**Comment by ddymko** [comment]
@cooperaj can you supply a `terraform plan` out?
