### ISSUE TITLE
[BUG] - Instance auto_backup is not expected

### ISSUE THREAD

**Issue by derrickmehaffy** [vultr/terraform-provider-vultr#92]
**Describe the bug**

Setting the instance `auto_backup` yields an error that the value is not expected.
Based on: https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/instance

Specifically:

> auto_backup - (Optional) Whether automatic backups will be enabled for this server (these have an extra charge associated with them).

**To Reproduce**

Attempt to set:

```
auto_backup = true
```

See Error:

```
Error: Unsupported argument

  on main.tf line 29, in resource "vultr_instance" "strapi_server":
  29:   auto_backup = var.strapi_server_auto_backup

An argument named "auto_backup" is not expected here.
```

Based on the Terraform plan response, it appears this variable is actually `backups`

**Expected behavior**

Terraform registry documentation is up to date :wink: 

**Screenshots**
N/A

**Desktop (please complete the following information where applicable:**
- OS: Linux Mint 20
- Terraform Version: v0.14.1
- Vultr Version: 2.1.0

**Comment by derrickmehaffy** [comment]
Thanks @ddymko I guess I picked the wrong day to start playing with Terraform and Vultr :laughing:

**Comment by ddymko** [comment]
@derrickmehaffy noooo! It's on us for missing some of these typos/issues in the docs from the v1 to v2 transition XD

If you find anything else or have any issues please feel free to create a ticket

**Comment by derrickmehaffy** [comment]
> If you find anything else or have any issues please feel free to create a ticket

Here or through the Vultr support portal? (And thanks for being so responsive, from one GitHub issue maintainer to another, it's nice :wink: )

**Comment by ddymko** [comment]
Either or - if you create a Vultr support ticket through the portal, relating to the open source, it will eventually trickle it's way to me so whichever you feel more comfortable with. Also not a problem try my best to help.
