### ISSUE TITLE
[BUG] - vultr_region does not return a result for a matching name

### ISSUE THREAD

**Issue by bbros-dev** [vultr/terraform-provider-vultr#98]
**Describe the bug**
Filtering the `vultr_region` resource returns no matches when you use a name in the API region list:

```bash
$ curl https://api.vultr.com/v1/regions/list |jq .
<snip>

  "19": {
    "DCID": "19",
    "name": "Sydney",
    "country": "AU",
    "continent": "Australia",
    "state": "",
    "ddos_protection": false,
    "block_storage": false,
    "regioncode": "SYD"
  }
}
```

**To Reproduce**
1. Set up a valid Terraform file that includes the following resource
```json
<snip>

data "vultr_region" "sydney" {
  filter {
    name   = "name"
    values = ["Sydney"]
  }
}

<snip>

```
2. Run:  `terraform init` and `terraform validate` ensure the result indicates a valid Terraform description.
3. Run: `terraform plan`
```bash
....
Error: no results were found

  on main.tf line 73, in data "vultr_region" "sydney":
  73: data "vultr_region" "sydney" {
```
**Expected behavior**
Expected the plan to complete without error.
Expected `data.vultr_region.sydney.id` to hold a value suitable to be passed to the `vultr_instance` resource.

**Screenshots**
NA

**Desktop (please complete the following information where applicable:**
 - OS: `Linux desktop.local.lan 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Language Version Terraform 0.13.5
 - Browser: NA
 - Version: Vultr plugin version 1.0.15

**Additional context**
NA

**Comment by ddymko** [comment]
We'll look into this

**Comment by bbros-dev** [comment]
I think this may be a versioning issue.  Closing until we have a repro.
