### ISSUE TITLE
[BUG] - vultr_firewall_rule: Error: expected subnet to contain a valid IP, got: 115.169.15.121

### ISSUE THREAD

**Issue by bbros-dev** [vultr/terraform-provider-vultr#99]
**Describe the bug**
When given a vlid IPv4 the  `vultr_firewall_rule` complains:

```bash
Error: expected subnet to contain a valid IP, got: 115.169.15.121
```

**To Reproduce**

```json
terraform {
  required_version = "~> 0.13.4"
  backend "local" {
    path = "/var/bastion.izhi.io/terraform.tfstate.d/terraform.tfstate"
    workspace_dir = "/var/bastion.izhi.io/terraform.tfstate.d"
  }
  required_providers {
    cloudflare = {
      source  = "registry.terraform.io/cloudflare/cloudflare"
      version = "~> 2.11.0"
    }
    http = {
      source  = "hashicorp/http"
      version = "~> 2.0.0"
    }
    vultr = {
      source = "vultr/vultr"
      version = "~> 2.1.1"
    }
  }
}

....

variable "allowed_ipv4s" {
  description = "Create Firewall whitelist rules for these IPv4 addresses."
  type        = list(string)
  default     = [
    "some-IPv4-here>"
    ]
}

...

data "http" "local_public_ipv4" {
  url = "http://ipv4.icanhazip.com"
}

...

## HTTPS
#
resource "vultr_firewall_rule" "https" {
  for_each = toset(concat(var.allowed_ipv4s,[data.http.local_public_ipv4.body]))

  firewall_group_id = vultr_firewall_group.bastion.id
  protocol = "tcp"
  ip_type = "v4"
  subnet = each.value
  subnet_size = "32"
  port = "443"
  notes = "TLS encrypted HTTP."
}

```
2. `terraform plan`
4. See error:
```bash
Error: expected subnet to contain a valid IP, got: 115.169.15.121
```

**Expected behavior**
Valid IPv4 address should be accepted.

**Screenshots**
NA

**Desktop (please complete the following information where applicable:**
See #98 

**Additional context**
NA

**Comment by bbros-dev** [comment]
We believe you need to `chomp` the given input string, or some such housekeeping, before deciding to reject it.

Workaround:

```bash
for_each = toset(concat(var.allowed_ipv4s,[chomp(data.http.local_public_ipv4.body)]))
```

Such sanitary/housekeeping work should be undertaken on all inputs before deciding to reject them - a common use case is to use Terraform in scenarios where output is passed along where such spurious non-printing characters often abound.

**Comment by ddymko** [comment]
@bbros-dev We are using terraforms IPValidation which then further checks if the IP is valid v4 or v6

https://github.com/vultr/terraform-provider-vultr/blob/master/vultr/resource_vultr_firewall_rule.go#L45

I think the solution to chomp your data prior to handing it off and then having the provider run an IP validation is the best approach.

**Comment by bbros-dev** [comment]
> We are using terraforms IPValidation which then further checks if the IP is valid v4 or v6

Ack. Better to sanitize strings in one place - the vultr provider -  instead of everyone having to decorate everything with `chomp` throughout all their Vultr TF files?

**Comment by ddymko** [comment]
@bbros-dev This will cause drift. Your statefile will have the `\n` and it is being read in from the data source and passed to the firewall resource. So if we remove any newlines in the provider any following `terraform plans/applys` will want to trigger a replacement because the local statefile will always differ from what is being received back from the API.

```
➜  tf-playground ta
vultr_firewall_group.test: Refreshing state... [id=58c88470-651c-4dc4-a448-c3793fa39b0a]
data.http.local_public_ipv4: Refreshing state... [id=http://ipv4.icanhazip.com]
vultr_firewall_rule.https: Refreshing state... [id=1]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # vultr_firewall_rule.https must be replaced
-/+ resource "vultr_firewall_rule" "https" {
        firewall_group_id = "58c88470-651c-4dc4-a448-c3793fa39b0a"
      ~ id                = "1" -> (known after apply)
        ip_type           = "v4"
        notes             = "TLS encrypted HTTP."
        port              = "443"
        protocol          = "tcp"
      ~ subnet            = <<~EOT # forces replacement
            24.46.206.153
        EOT
        subnet_size       = 32
    }
```

```
data "http" "local_public_ipv4" {
  url = "http://ipv4.icanhazip.com"
}


resource "vultr_firewall_group" "test" {
 description = "test"
}

resource "vultr_firewall_rule" "https" {
  firewall_group_id = vultr_firewall_group.test.id
  protocol = "tcp"
  ip_type = "v4"
  subnet = data.http.local_public_ipv4.body
  subnet_size = "32"
  port = "443"
  notes = "TLS encrypted HTTP."
}
```
